import { Country } from './types';

export const countryInformation: Country[] = [
  {
    iso2: 'AD',
    name: 'Andorra',
    native: 'Andorra',
    dialCode: '376',
    continent_name: 'EU',
    capital: 'Andorra la Vella',
    currency: 'EUR',
    languages: ['ca'],
    emoji: '🇦🇩',
    emojiU: 'U+1F1E6 U+1F1E9',
  },
  {
    iso2: 'AE',
    name: 'United Arab Emirates',
    native: 'دولة الإمارات العربية المتحدة',
    dialCode: '971',
    continent_name: 'AS',
    capital: 'Abu Dhabi',
    currency: 'AED',
    languages: ['ar'],
    emoji: '🇦🇪',
    emojiU: 'U+1F1E6 U+1F1EA',
  },
  {
    iso2: 'AF',
    name: 'Afghanistan',
    native: 'افغانستان',
    dialCode: '93',
    continent_name: 'AS',
    capital: 'Kabul',
    currency: 'AFN',
    languages: ['ps', 'uz', 'tk'],
    emoji: '🇦🇫',
    emojiU: 'U+1F1E6 U+1F1EB',
  },
  {
    iso2: 'AG',
    name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    dialCode: '1',
    continent_name: 'NA',
    capital: "Saint John's",
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇬',
    emojiU: 'U+1F1E6 U+1F1EC',
  },
  {
    iso2: 'AI',
    name: 'Anguilla',
    native: 'Anguilla',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'The Valley',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇮',
    emojiU: 'U+1F1E6 U+1F1EE',
  },
  {
    iso2: 'AL',
    name: 'Albania',
    native: 'Shqipëria',
    dialCode: '355',
    continent_name: 'EU',
    capital: 'Tirana',
    currency: 'ALL',
    languages: ['sq'],
    emoji: '🇦🇱',
    emojiU: 'U+1F1E6 U+1F1F1',
  },
  {
    iso2: 'AM',
    name: 'Armenia',
    native: 'Հայաստան',
    dialCode: '374',
    continent_name: 'AS',
    capital: 'Yerevan',
    currency: 'AMD',
    languages: ['hy', 'ru'],
    emoji: '🇦🇲',
    emojiU: 'U+1F1E6 U+1F1F2',
  },
  {
    iso2: 'AO',
    name: 'Angola',
    native: 'Angola',
    dialCode: '244',
    continent_name: 'AF',
    capital: 'Luanda',
    currency: 'AOA',
    languages: ['pt'],
    emoji: '🇦🇴',
    emojiU: 'U+1F1E6 U+1F1F4',
  },
  {
    iso2: 'AQ',
    name: 'Antarctica',
    native: 'Antarctica',
    dialCode: '672',
    continent_name: 'AN',
    capital: '',
    currency: '',
    languages: [],
    emoji: '🇦🇶',
    emojiU: 'U+1F1E6 U+1F1F6',
    invalid: true,
  },
  {
    iso2: 'AR',
    name: 'Argentina',
    native: 'Argentina',
    dialCode: '54',
    continent_name: 'SA',
    capital: 'Buenos Aires',
    currency: 'ARS',
    languages: ['es', 'gn'],
    emoji: '🇦🇷',
    emojiU: 'U+1F1E6 U+1F1F7',
  },
  {
    iso2: 'AS',
    name: 'American Samoa',
    native: 'American Samoa',
    dialCode: '1',
    continent_name: 'OC',
    capital: 'Pago Pago',
    currency: 'USD',
    languages: ['en', 'sm'],
    emoji: '🇦🇸',
    emojiU: 'U+1F1E6 U+1F1F8',
  },
  {
    iso2: 'AT',
    name: 'Austria',
    native: 'Österreich',
    dialCode: '43',
    continent_name: 'EU',
    capital: 'Vienna',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇦🇹',
    emojiU: 'U+1F1E6 U+1F1F9',
  },
  {
    iso2: 'AU',
    name: 'Australia',
    native: 'Australia',
    dialCode: '61',
    continent_name: 'OC',
    capital: 'Canberra',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇦🇺',
    emojiU: 'U+1F1E6 U+1F1FA',
  },
  {
    iso2: 'AW',
    name: 'Aruba',
    native: 'Aruba',
    dialCode: '297',
    continent_name: 'NA',
    capital: 'Oranjestad',
    currency: 'AWG',
    languages: ['nl', 'pa'],
    emoji: '🇦🇼',
    emojiU: 'U+1F1E6 U+1F1FC',
  },
  {
    iso2: 'AX',
    name: 'Åland Islands',
    dialCode: '358',
    native: 'Suomi',
    continent_name: 'EU',
    capital: 'Helsinki',
    currency: 'EUR',
    languages: ['fi', 'sv'],
    emoji: '🇫🇮',
    emojiU: 'U+1F1EB U+1F1EE',
  },
  {
    iso2: 'AZ',
    name: 'Azerbaijan',
    native: 'Azərbaycan',
    dialCode: '994',
    continent_name: 'AS',
    capital: 'Baku',
    currency: 'AZN',
    languages: ['az'],
    emoji: '🇦🇿',
    emojiU: 'U+1F1E6 U+1F1FF',
  },
  {
    iso2: 'BA',
    name: 'Bosnia and Herzegovina',
    native: 'Bosna i Hercegovina',
    dialCode: '387',
    continent_name: 'EU',
    capital: 'Sarajevo',
    currency: 'BAM',
    languages: ['bs', 'hr', 'sr'],
    emoji: '🇧🇦',
    emojiU: 'U+1F1E7 U+1F1E6',
  },
  {
    iso2: 'BB',
    name: 'Barbados',
    native: 'Barbados',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'Bridgetown',
    currency: 'BBD',
    languages: ['en'],
    emoji: '🇧🇧',
    emojiU: 'U+1F1E7 U+1F1E7',
  },
  {
    iso2: 'BD',
    name: 'Bangladesh',
    native: 'Bangladesh',
    dialCode: '880',
    continent_name: 'AS',
    capital: 'Dhaka',
    currency: 'BDT',
    languages: ['bn'],
    emoji: '🇧🇩',
    emojiU: 'U+1F1E7 U+1F1E9',
  },
  {
    iso2: 'BE',
    name: 'Belgium',
    native: 'België',
    dialCode: '32',
    continent_name: 'EU',
    capital: 'Brussels',
    currency: 'EUR',
    languages: ['nl', 'fr', 'de'],
    emoji: '🇧🇪',
    emojiU: 'U+1F1E7 U+1F1EA',
  },
  {
    iso2: 'BF',
    name: 'Burkina Faso',
    native: 'Burkina Faso',
    dialCode: '226',
    continent_name: 'AF',
    capital: 'Ouagadougou',
    currency: 'XOF',
    languages: ['fr', 'ff'],
    emoji: '🇧🇫',
    emojiU: 'U+1F1E7 U+1F1EB',
  },
  {
    iso2: 'BG',
    name: 'Bulgaria',
    native: 'България',
    dialCode: '359',
    continent_name: 'EU',
    capital: 'Sofia',
    currency: 'BGN',
    languages: ['bg'],
    emoji: '🇧🇬',
    emojiU: 'U+1F1E7 U+1F1EC',
  },
  {
    iso2: 'BH',
    name: 'Bahrain',
    native: '‏البحرين',
    dialCode: '973',
    continent_name: 'AS',
    capital: 'Manama',
    currency: 'BHD',
    languages: ['ar'],
    emoji: '🇧🇭',
    emojiU: 'U+1F1E7 U+1F1ED',
  },
  {
    iso2: 'BI',
    name: 'Burundi',
    native: 'Burundi',
    dialCode: '257',
    continent_name: 'AF',
    capital: 'Bujumbura',
    currency: 'BIF',
    languages: ['fr', 'rn'],
    emoji: '🇧🇮',
    emojiU: 'U+1F1E7 U+1F1EE',
  },
  {
    iso2: 'BJ',
    name: 'Benin',
    native: 'Bénin',
    dialCode: '229',
    continent_name: 'AF',
    capital: 'Porto-Novo',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇧🇯',
    emojiU: 'U+1F1E7 U+1F1EF',
  },
  {
    iso2: 'BL',
    name: 'Saint Barthélemy',
    native: 'Saint-Barthélemy',
    dialCode: '590',
    continent_name: 'NA',
    capital: 'Gustavia',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇧🇱',
    emojiU: 'U+1F1E7 U+1F1F1',
  },
  {
    iso2: 'BM',
    name: 'Bermuda',
    native: 'Bermuda',
    dialCode: '1441',
    continent_name: 'NA',
    capital: 'Hamilton',
    currency: 'BMD',
    languages: ['en'],
    emoji: '🇧🇲',
    emojiU: 'U+1F1E7 U+1F1F2',
  },
  {
    iso2: 'BN',
    name: 'Brunei Darussalam',
    dialCode: '673',
    native: 'Negara Brunei Darussalam',
    continent_name: 'AS',
    capital: 'Bandar Seri Begawan',
    currency: 'BND',
    languages: ['ms'],
    emoji: '🇧🇳',
    emojiU: 'U+1F1E7 U+1F1F3',
  },
  {
    iso2: 'BO',
    name: 'Bolivia, Plurinational State of',
    dialCode: '591',
    native: 'Bolivia',
    continent_name: 'SA',
    capital: 'Sucre',
    currency: 'BOB,BOV',
    languages: ['es', 'ay', 'qu'],
    emoji: '🇧🇴',
    emojiU: 'U+1F1E7 U+1F1F4',
  },
  {
    iso2: 'CW',
    name: 'Curaçao',
    dialCode: '599',
    native: 'Curaçao',
    continent_name: 'NA',
    capital: 'Willemstad',
    currency: 'ANG',
    languages: ['nl', 'pa', 'en'],
    emoji: '🇨🇼',
    emojiU: 'U+1F1E8 U+1F1FC',
  },
  {
    iso2: 'BR',
    name: 'Brazil',
    native: 'Brasil',
    dialCode: '55',
    continent_name: 'SA',
    capital: 'Brasília',
    currency: 'BRL',
    languages: ['pt'],
    emoji: '🇧🇷',
    emojiU: 'U+1F1E7 U+1F1F7',
  },
  {
    iso2: 'BS',
    name: 'Bahamas',
    native: 'Bahamas',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'Nassau',
    currency: 'BSD',
    languages: ['en'],
    emoji: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
  },
  {
    iso2: 'BT',
    name: 'Bhutan',
    native: 'ʼbrug-yul',
    dialCode: '975',
    continent_name: 'AS',
    capital: 'Thimphu',
    currency: 'BTN,INR',
    languages: ['dz'],
    emoji: '🇧🇹',
    emojiU: 'U+1F1E7 U+1F1F9',
  },
  {
    iso2: 'BV',
    name: 'Bouvet Island',
    native: 'Bouvetøya',
    dialCode: '47',
    continent_name: 'AN',
    capital: '',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇧🇻',
    emojiU: 'U+1F1E7 U+1F1FB',
    invalid: true,
  },
  {
    iso2: 'BW',
    name: 'Botswana',
    native: 'Botswana',
    dialCode: '267',
    continent_name: 'AF',
    capital: 'Gaborone',
    currency: 'BWP',
    languages: ['en', 'tn'],
    emoji: '🇧🇼',
    emojiU: 'U+1F1E7 U+1F1FC',
  },
  {
    iso2: 'BY',
    name: 'Belarus',
    native: 'Белару́сь',
    dialCode: '375',
    continent_name: 'EU',
    capital: 'Minsk',
    currency: 'BYN',
    languages: ['be', 'ru'],
    emoji: '🇧🇾',
    emojiU: 'U+1F1E7 U+1F1FE',
  },
  {
    iso2: 'BZ',
    name: 'Belize',
    native: 'Belize',
    dialCode: '501',
    continent_name: 'NA',
    capital: 'Belmopan',
    currency: 'BZD',
    languages: ['en', 'es'],
    emoji: '🇧🇿',
    emojiU: 'U+1F1E7 U+1F1FF',
  },
  {
    iso2: 'AG',
    name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    dialCode: '1',
    continent_name: 'NA',
    capital: "Saint John's",
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇬',
    emojiU: 'U+1F1E6 U+1F1EC',
  },
  {
    iso2: 'CC',
    name: 'Cocos (Keeling) Islands',
    dialCode: '61',
    native: 'Heard Island and McDonald Islands',
    continent_name: 'AN',
    capital: '',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇭🇲',
    emojiU: 'U+1F1ED U+1F1F2',
  },
  {
    iso2: 'CD',
    name: 'Congo, Democratic Republic of the',
    dialCode: '243',
    native: 'République démocratique du Congo',
    continent_name: 'AF',
    capital: 'Kinshasa',
    currency: 'CDF',
    languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
    emoji: '🇨🇩',
    emojiU: 'U+1F1E8 U+1F1E9',
  },
  {
    iso2: 'CF',
    name: 'Central African Republic',
    native: 'Ködörösêse tî Bêafrîka',
    dialCode: '236',
    continent_name: 'AF',
    capital: 'Bangui',
    currency: 'XAF',
    languages: ['fr', 'sg'],
    emoji: '🇨🇫',
    emojiU: 'U+1F1E8 U+1F1EB',
  },
  {
    iso2: 'CG',
    name: 'Congo',
    dialCode: '242',
    native: 'République du Congo',
    continent_name: 'AF',
    capital: 'Brazzaville',
    currency: 'XAF',
    languages: ['fr', 'ln'],
    emoji: '🇨🇬',
    emojiU: 'U+1F1E8 U+1F1EC',
  },
  {
    iso2: 'CH',
    name: 'Switzerland',
    native: 'Schweiz',
    dialCode: '41',
    continent_name: 'EU',
    capital: 'Bern',
    currency: 'CHE,CHF,CHW',
    languages: ['de', 'fr', 'it'],
    emoji: '🇨🇭',
    emojiU: 'U+1F1E8 U+1F1ED',
  },
  {
    iso2: 'CI',
    name: "Côte d'Ivoire",
    dialCode: '225',
    native: "Côte d'Ivoire",
    continent_name: 'AF',
    capital: 'Yamoussoukro',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇨🇮',
    emojiU: 'U+1F1E8 U+1F1EE',
  },
  {
    iso2: 'CK',
    name: 'Cook Islands',
    native: 'Cook Islands',
    dialCode: '682',
    continent_name: 'OC',
    capital: 'Avarua',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇨🇰',
    emojiU: 'U+1F1E8 U+1F1F0',
  },
  {
    iso2: 'CL',
    name: 'Chile',
    native: 'Chile',
    dialCode: '56',
    continent_name: 'SA',
    capital: 'Santiago',
    currency: 'CLF,CLP',
    languages: ['es'],
    emoji: '🇨🇱',
    emojiU: 'U+1F1E8 U+1F1F1',
  },
  {
    iso2: 'CM',
    name: 'Cameroon',
    native: 'Cameroon',
    dialCode: '237',
    continent_name: 'AF',
    capital: 'Yaoundé',
    currency: 'XAF',
    languages: ['en', 'fr'],
    emoji: '🇨🇲',
    emojiU: 'U+1F1E8 U+1F1F2',
  },
  {
    iso2: 'CN',
    name: 'China',
    native: '中国',
    dialCode: '86',
    continent_name: 'AS',
    capital: 'Beijing',
    currency: 'CNY',
    languages: ['zh'],
    emoji: '🇨🇳',
    emojiU: 'U+1F1E8 U+1F1F3',
  },
  {
    iso2: 'CO',
    name: 'Colombia',
    native: 'Colombia',
    dialCode: '57',
    continent_name: 'SA',
    capital: 'Bogotá',
    currency: 'COP',
    languages: ['es'],
    emoji: '🇨🇴',
    emojiU: 'U+1F1E8 U+1F1F4',
  },
  {
    iso2: 'CR',
    name: 'Costa Rica',
    native: 'Costa Rica',
    dialCode: '506',
    continent_name: 'NA',
    capital: 'San José',
    currency: 'CRC',
    languages: ['es'],
    emoji: '🇨🇷',
    emojiU: 'U+1F1E8 U+1F1F7',
  },
  {
    iso2: 'CU',
    name: 'Cuba',
    native: 'Cuba',
    dialCode: '53',
    continent_name: 'NA',
    capital: 'Havana',
    currency: 'CUC,CUP',
    languages: ['es'],
    emoji: '🇨🇺',
    emojiU: 'U+1F1E8 U+1F1FA',
  },
  {
    iso2: 'CV',
    name: 'Cabo Verde',
    dialCode: '238',
    native: 'Cabo Verde',
    continent_name: 'AF',
    capital: 'Praia',
    currency: 'CVE',
    languages: ['pt'],
    emoji: '🇨🇻',
    emojiU: 'U+1F1E8 U+1F1FB',
  },
  {
    iso2: 'CW',
    name: 'Curaçao',
    dialCode: '599',
    native: 'Curaçao',
    continent_name: 'NA',
    capital: 'Willemstad',
    currency: 'ANG',
    languages: ['nl', 'pa', 'en'],
    emoji: '🇨🇼',
    emojiU: 'U+1F1E8 U+1F1FC',
  },
  {
    iso2: 'CX',
    name: 'Christmas Island',
    native: 'Christmas Island',
    dialCode: '61',
    continent_name: 'AS',
    capital: 'Flying Fish Cove',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇨🇽',
    emojiU: 'U+1F1E8 U+1F1FD',
  },
  {
    iso2: 'CY',
    name: 'Cyprus',
    native: 'Κύπρος',
    dialCode: '357',
    continent_name: 'EU',
    capital: 'Nicosia',
    currency: 'EUR',
    languages: ['el', 'tr', 'hy'],
    emoji: '🇨🇾',
    emojiU: 'U+1F1E8 U+1F1FE',
  },
  {
    iso2: 'CZ',
    name: 'Czechia',
    dialCode: '420',
    native: 'Česká republika',
    continent_name: 'EU',
    capital: 'Prague',
    currency: 'CZK',
    languages: ['cs', 'sk'],
    emoji: '🇨🇿',
    emojiU: 'U+1F1E8 U+1F1FF',
  },
  {
    iso2: 'DE',
    name: 'Germany',
    native: 'Deutschland',
    dialCode: '49',
    continent_name: 'EU',
    capital: 'Berlin',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇩🇪',
    emojiU: 'U+1F1E9 U+1F1EA',
  },
  {
    iso2: 'DJ',
    name: 'Djibouti',
    native: 'Djibouti',
    dialCode: '253',
    continent_name: 'AF',
    capital: 'Djibouti',
    currency: 'DJF',
    languages: ['fr', 'ar'],
    emoji: '🇩🇯',
    emojiU: 'U+1F1E9 U+1F1EF',
  },
  {
    iso2: 'DK',
    name: 'Denmark',
    native: 'Danmark',
    dialCode: '45',
    continent_name: 'EU',
    capital: 'Copenhagen',
    currency: 'DKK',
    languages: ['da'],
    emoji: '🇩🇰',
    emojiU: 'U+1F1E9 U+1F1F0',
  },
  {
    iso2: 'DM',
    name: 'Dominica',
    native: 'Dominica',
    dialCode: '1767',
    continent_name: 'NA',
    capital: 'Roseau',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇩🇲',
    emojiU: 'U+1F1E9 U+1F1F2',
  },
  {
    iso2: 'AI',
    name: 'Anguilla',
    native: 'Anguilla',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'The Valley',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇮',
    emojiU: 'U+1F1E6 U+1F1EE',
  },
  {
    iso2: 'DZ',
    name: 'Algeria',
    native: 'الجزائر',
    dialCode: '213',
    continent_name: 'AF',
    capital: 'Algiers',
    currency: 'DZD',
    languages: ['ar'],
    emoji: '🇩🇿',
    emojiU: 'U+1F1E9 U+1F1FF',
  },
  {
    iso2: 'EC',
    name: 'Ecuador',
    native: 'Ecuador',
    dialCode: '593',
    continent_name: 'SA',
    capital: 'Quito',
    currency: 'USD',
    languages: ['es'],
    emoji: '🇪🇨',
    emojiU: 'U+1F1EA U+1F1E8',
  },
  {
    iso2: 'EE',
    name: 'Estonia',
    native: 'Eesti',
    dialCode: '372',
    continent_name: 'EU',
    capital: 'Tallinn',
    currency: 'EUR',
    languages: ['et'],
    emoji: '🇪🇪',
    emojiU: 'U+1F1EA U+1F1EA',
  },
  {
    iso2: 'EG',
    name: 'Egypt',
    native: 'مصر‎',
    dialCode: '20',
    continent_name: 'AF',
    capital: 'Cairo',
    currency: 'EGP',
    languages: ['ar'],
    emoji: '🇪🇬',
    emojiU: 'U+1F1EA U+1F1EC',
  },
  {
    iso2: 'EH',
    name: 'Western Sahara',
    native: 'الصحراء الغربية',
    dialCode: '212',
    continent_name: 'AF',
    capital: 'El Aaiún',
    currency: 'MAD,DZD,MRU',
    languages: ['es'],
    emoji: '🇪🇭',
    emojiU: 'U+1F1EA U+1F1ED',
  },
  {
    iso2: 'ER',
    name: 'Eritrea',
    native: 'ኤርትራ',
    dialCode: '291',
    continent_name: 'AF',
    capital: 'Asmara',
    currency: 'ERN',
    languages: ['ti', 'ar', 'en'],
    emoji: '🇪🇷',
    emojiU: 'U+1F1EA U+1F1F7',
  },
  {
    iso2: 'ES',
    name: 'Spain',
    native: 'España',
    dialCode: '34',
    continent_name: 'EU',
    capital: 'Madrid',
    currency: 'EUR',
    languages: ['es', 'eu', 'ca', 'gl', 'oc'],
    emoji: '🇪🇸',
    emojiU: 'U+1F1EA U+1F1F8',
  },
  {
    iso2: 'ET',
    name: 'Ethiopia',
    native: 'ኢትዮጵያ',
    dialCode: '251',
    continent_name: 'AF',
    capital: 'Addis Ababa',
    currency: 'ETB',
    languages: ['am'],
    emoji: '🇪🇹',
    emojiU: 'U+1F1EA U+1F1F9',
  },
  {
    iso2: 'FI',
    name: 'Finland',
    native: 'Suomi',
    dialCode: '358',
    continent_name: 'EU',
    capital: 'Helsinki',
    currency: 'EUR',
    languages: ['fi', 'sv'],
    emoji: '🇫🇮',
    emojiU: 'U+1F1EB U+1F1EE',
  },
  {
    iso2: 'FJ',
    name: 'Fiji',
    native: 'Fiji',
    dialCode: '679',
    continent_name: 'OC',
    capital: 'Suva',
    currency: 'FJD',
    languages: ['en', 'fj', 'hi', 'ur'],
    emoji: '🇫🇯',
    emojiU: 'U+1F1EB U+1F1EF',
  },
  {
    iso2: 'FK',
    name: 'Falkland Islands (Malvinas)',
    dialCode: '500',
    native: 'Falkland Islands',
    continent_name: 'SA',
    capital: 'Stanley',
    currency: 'FKP',
    languages: ['en'],
    emoji: '🇫🇰',
    emojiU: 'U+1F1EB U+1F1F0',
  },
  {
    iso2: 'FM',
    name: 'Micronesia, Federated States of',
    dialCode: '691',
    native: 'Micronesia',
    continent_name: 'OC',
    capital: 'Palikir',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇫🇲',
    emojiU: 'U+1F1EB U+1F1F2',
  },
  {
    iso2: 'FO',
    name: 'Faroe Islands',
    native: 'Føroyar',
    dialCode: '298',
    continent_name: 'EU',
    capital: 'Tórshavn',
    currency: 'DKK',
    languages: ['fo'],
    emoji: '🇫🇴',
    emojiU: 'U+1F1EB U+1F1F4',
  },
  {
    iso2: 'FR',
    name: 'France',
    native: 'France',
    dialCode: '33',
    continent_name: 'EU',
    capital: 'Paris',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇫🇷',
    emojiU: 'U+1F1EB U+1F1F7',
  },
  {
    iso2: 'GA',
    name: 'Gabon',
    native: 'Gabon',
    dialCode: '241',
    continent_name: 'AF',
    capital: 'Libreville',
    currency: 'XAF',
    languages: ['fr'],
    emoji: '🇬🇦',
    emojiU: 'U+1F1EC U+1F1E6',
  },
  {
    iso2: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    dialCode: '44',
    native: 'United Kingdom',
    continent_name: 'EU',
    capital: 'London',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇧',
    emojiU: 'U+1F1EC U+1F1E7',
  },
  {
    iso2: 'GD',
    name: 'Grenada',
    native: 'Grenada',
    dialCode: '1473',
    continent_name: 'NA',
    capital: "St. George's",
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇬🇩',
    emojiU: 'U+1F1EC U+1F1E9',
  },
  {
    iso2: 'GE',
    name: 'Georgia',
    native: 'საქართველო',
    dialCode: '995',
    continent_name: 'AS',
    capital: 'Tbilisi',
    currency: 'GEL',
    languages: ['ka'],
    emoji: '🇬🇪',
    emojiU: 'U+1F1EC U+1F1EA',
  },
  {
    iso2: 'GF',
    name: 'French Guiana',
    native: 'Guyane française',
    dialCode: '594',
    continent_name: 'SA',
    capital: 'Cayenne',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇫',
    emojiU: 'U+1F1EC U+1F1EB',
  },
  {
    iso2: 'GG',
    name: 'Guernsey',
    native: 'Guernsey',
    dialCode: '44',
    continent_name: 'EU',
    capital: 'St. Peter Port',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇬🇬',
    emojiU: 'U+1F1EC U+1F1EC',
  },
  {
    iso2: 'GH',
    name: 'Ghana',
    native: 'Ghana',
    dialCode: '233',
    continent_name: 'AF',
    capital: 'Accra',
    currency: 'GHS',
    languages: ['en'],
    emoji: '🇬🇭',
    emojiU: 'U+1F1EC U+1F1ED',
  },
  {
    iso2: 'GI',
    name: 'Gibraltar',
    native: 'Gibraltar',
    dialCode: '350',
    continent_name: 'EU',
    capital: 'Gibraltar',
    currency: 'GIP',
    languages: ['en'],
    emoji: '🇬🇮',
    emojiU: 'U+1F1EC U+1F1EE',
  },
  {
    iso2: 'GL',
    name: 'Greenland',
    native: 'Kalaallit Nunaat',
    dialCode: '299',
    continent_name: 'NA',
    capital: 'Nuuk',
    currency: 'DKK',
    languages: ['kl'],
    emoji: '🇬🇱',
    emojiU: 'U+1F1EC U+1F1F1',
  },
  {
    iso2: 'GM',
    name: 'Gambia',
    native: 'Gambia',
    dialCode: '220',
    continent_name: 'AF',
    capital: 'Banjul',
    currency: 'GMD',
    languages: ['en'],
    emoji: '🇬🇲',
    emojiU: 'U+1F1EC U+1F1F2',
  },
  {
    iso2: 'GN',
    name: 'Guinea',
    native: 'Guinée',
    dialCode: '224',
    continent_name: 'AF',
    capital: 'Conakry',
    currency: 'GNF',
    languages: ['fr', 'ff'],
    emoji: '🇬🇳',
    emojiU: 'U+1F1EC U+1F1F3',
  },
  {
    iso2: 'GP',
    name: 'Guadeloupe',
    native: 'Guadeloupe',
    dialCode: '590',
    continent_name: 'NA',
    capital: 'Basse-Terre',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇵',
    emojiU: 'U+1F1EC U+1F1F5',
  },
  {
    iso2: 'GQ',
    name: 'Equatorial Guinea',
    native: 'Guinea Ecuatorial',
    dialCode: '240',
    continent_name: 'AF',
    capital: 'Malabo',
    currency: 'XAF',
    languages: ['es', 'fr'],
    emoji: '🇬🇶',
    emojiU: 'U+1F1EC U+1F1F6',
  },
  {
    iso2: 'GR',
    name: 'Greece',
    native: 'Ελλάδα',
    dialCode: '30',
    continent_name: 'EU',
    capital: 'Athens',
    currency: 'EUR',
    languages: ['el'],
    emoji: '🇬🇷',
    emojiU: 'U+1F1EC U+1F1F7',
  },
  {
    iso2: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    native: 'South Georgia',
    dialCode: '500',
    continent_name: 'AN',
    capital: 'King Edward Point',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇸',
    emojiU: 'U+1F1EC U+1F1F8',
    invalid: true,
  },
  {
    iso2: 'GT',
    name: 'Guatemala',
    native: 'Guatemala',
    dialCode: '502',
    continent_name: 'NA',
    capital: 'Guatemala City',
    currency: 'GTQ',
    languages: ['es'],
    emoji: '🇬🇹',
    emojiU: 'U+1F1EC U+1F1F9',
  },
  {
    iso2: 'GU',
    name: 'Guam',
    native: 'Guam',
    dialCode: '1671',
    continent_name: 'OC',
    capital: 'Hagåtña',
    currency: 'USD',
    languages: ['en', 'ch', 'es'],
    emoji: '🇬🇺',
    emojiU: 'U+1F1EC U+1F1FA',
  },
  {
    iso2: 'GW',
    name: 'Guinea-Bissau',
    native: 'Guiné-Bissau',
    dialCode: '245',
    continent_name: 'AF',
    capital: 'Bissau',
    currency: 'XOF',
    languages: ['pt'],
    emoji: '🇬🇼',
    emojiU: 'U+1F1EC U+1F1FC',
  },
  {
    iso2: 'GY',
    name: 'Guyana',
    native: 'Guyana',
    dialCode: '592',
    continent_name: 'SA',
    capital: 'Georgetown',
    currency: 'GYD',
    languages: ['en'],
    emoji: '🇬🇾',
    emojiU: 'U+1F1EC U+1F1FE',
  },
  {
    iso2: 'HK',
    name: 'Hong Kong',
    native: '香港',
    dialCode: '852',
    continent_name: 'AS',
    capital: 'City of Victoria',
    currency: 'HKD',
    languages: ['zh', 'en'],
    emoji: '🇭🇰',
    emojiU: 'U+1F1ED U+1F1F0',
  },
  {
    iso2: 'HM',
    name: 'Heard Island and McDonald Islands',
    native: 'Heard Island and McDonald Islands',
    dialCode: '672',
    continent_name: 'AN',
    capital: '',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇭🇲',
    emojiU: 'U+1F1ED U+1F1F2',
    invalid: true,
  },
  {
    iso2: 'HN',
    name: 'Honduras',
    native: 'Honduras',
    dialCode: '504',
    continent_name: 'NA',
    capital: 'Tegucigalpa',
    currency: 'HNL',
    languages: ['es'],
    emoji: '🇭🇳',
    emojiU: 'U+1F1ED U+1F1F3',
  },
  {
    iso2: 'HR',
    name: 'Croatia',
    native: 'Hrvatska',
    dialCode: '385',
    continent_name: 'EU',
    capital: 'Zagreb',
    currency: 'HRK',
    languages: ['hr'],
    emoji: '🇭🇷',
    emojiU: 'U+1F1ED U+1F1F7',
  },
  {
    iso2: 'HT',
    name: 'Haiti',
    native: 'Haïti',
    dialCode: '509',
    continent_name: 'NA',
    capital: 'Port-au-Prince',
    currency: 'HTG,USD',
    languages: ['fr', 'ht'],
    emoji: '🇭🇹',
    emojiU: 'U+1F1ED U+1F1F9',
  },
  {
    iso2: 'HU',
    name: 'Hungary',
    native: 'Magyarország',
    dialCode: '36',
    continent_name: 'EU',
    capital: 'Budapest',
    currency: 'HUF',
    languages: ['hu'],
    emoji: '🇭🇺',
    emojiU: 'U+1F1ED U+1F1FA',
  },
  {
    iso2: 'ID',
    name: 'Indonesia',
    native: 'Indonesia',
    dialCode: '62',
    continent_name: 'AS',
    capital: 'Jakarta',
    currency: 'IDR',
    languages: ['id'],
    emoji: '🇮🇩',
    emojiU: 'U+1F1EE U+1F1E9',
  },
  {
    iso2: 'IE',
    name: 'Ireland',
    native: 'Éire',
    dialCode: '353',
    continent_name: 'EU',
    capital: 'Dublin',
    currency: 'EUR',
    languages: ['ga', 'en'],
    emoji: '🇮🇪',
    emojiU: 'U+1F1EE U+1F1EA',
  },
  {
    iso2: 'IL',
    name: 'Israel',
    native: 'יִשְׂרָאֵל',
    dialCode: '972',
    continent_name: 'AS',
    capital: 'Jerusalem',
    currency: 'ILS',
    languages: ['he', 'ar'],
    emoji: '🇮🇱',
    emojiU: 'U+1F1EE U+1F1F1',
  },
  {
    iso2: 'IM',
    name: 'Isle of Man',
    native: 'Isle of Man',
    dialCode: '44',
    continent_name: 'EU',
    capital: 'Douglas',
    currency: 'GBP',
    languages: ['en', 'gv'],
    emoji: '🇮🇲',
    emojiU: 'U+1F1EE U+1F1F2',
  },
  {
    iso2: 'IN',
    name: 'India',
    native: 'भारत',
    dialCode: '91',
    continent_name: 'AS',
    capital: 'New Delhi',
    currency: 'INR',
    languages: ['hi', 'en'],
    emoji: '🇮🇳',
    emojiU: 'U+1F1EE U+1F1F3',
  },
  {
    iso2: 'IO',
    name: 'British Indian Ocean Territory',
    native: 'British Indian Ocean Territory',
    dialCode: '246',
    continent_name: 'AS',
    capital: 'Diego Garcia',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇮🇴',
    emojiU: 'U+1F1EE U+1F1F4',
  },
  {
    iso2: 'IQ',
    name: 'Iraq',
    native: 'العراق',
    dialCode: '964',
    continent_name: 'AS',
    capital: 'Baghdad',
    currency: 'IQD',
    languages: ['ar', 'ku'],
    emoji: '🇮🇶',
    emojiU: 'U+1F1EE U+1F1F6',
  },
  {
    iso2: 'IR',
    name: 'Iran, Islamic Republic of',
    dialCode: '98',
    native: 'ایران',
    continent_name: 'AS',
    capital: 'Tehran',
    currency: 'IRR',
    languages: ['fa'],
    emoji: '🇮🇷',
    emojiU: 'U+1F1EE U+1F1F7',
  },
  {
    iso2: 'IS',
    name: 'Iceland',
    native: 'Ísland',
    dialCode: '354',
    continent_name: 'EU',
    capital: 'Reykjavik',
    currency: 'ISK',
    languages: ['is'],
    emoji: '🇮🇸',
    emojiU: 'U+1F1EE U+1F1F8',
  },
  {
    iso2: 'IT',
    name: 'Italy',
    native: 'Italia',
    dialCode: '39',
    continent_name: 'EU',
    capital: 'Rome',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇮🇹',
    emojiU: 'U+1F1EE U+1F1F9',
  },
  {
    iso2: 'JE',
    name: 'Jersey',
    native: 'Jersey',
    dialCode: '44',
    continent_name: 'EU',
    capital: 'Saint Helier',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇯🇪',
    emojiU: 'U+1F1EF U+1F1EA',
  },
  {
    iso2: 'JM',
    name: 'Jamaica',
    native: 'Jamaica',
    dialCode: '1876',
    continent_name: 'NA',
    capital: 'Kingston',
    currency: 'JMD',
    languages: ['en'],
    emoji: '🇯🇲',
    emojiU: 'U+1F1EF U+1F1F2',
  },
  {
    iso2: 'JO',
    name: 'Jordan',
    native: 'الأردن',
    dialCode: '962',
    continent_name: 'AS',
    capital: 'Amman',
    currency: 'JOD',
    languages: ['ar'],
    emoji: '🇯🇴',
    emojiU: 'U+1F1EF U+1F1F4',
  },
  {
    iso2: 'JP',
    name: 'Japan',
    native: '日本',
    dialCode: '81',
    continent_name: 'AS',
    capital: 'Tokyo',
    currency: 'JPY',
    languages: ['ja'],
    emoji: '🇯🇵',
    emojiU: 'U+1F1EF U+1F1F5',
  },
  {
    iso2: 'KE',
    name: 'Kenya',
    native: 'Kenya',
    dialCode: '254',
    continent_name: 'AF',
    capital: 'Nairobi',
    currency: 'KES',
    languages: ['en', 'sw'],
    emoji: '🇰🇪',
    emojiU: 'U+1F1F0 U+1F1EA',
  },
  {
    iso2: 'KG',
    name: 'Kyrgyzstan',
    native: 'Кыргызстан',
    dialCode: '996',
    continent_name: 'AS',
    capital: 'Bishkek',
    currency: 'KGS',
    languages: ['ky', 'ru'],
    emoji: '🇰🇬',
    emojiU: 'U+1F1F0 U+1F1EC',
  },
  {
    iso2: 'KH',
    name: 'Cambodia',
    native: 'Kâmpŭchéa',
    dialCode: '855',
    continent_name: 'AS',
    capital: 'Phnom Penh',
    currency: 'KHR',
    languages: ['km'],
    emoji: '🇰🇭',
    emojiU: 'U+1F1F0 U+1F1ED',
  },
  {
    iso2: 'KI',
    name: 'Kiribati',
    native: 'Kiribati',
    dialCode: '686',
    continent_name: 'OC',
    capital: 'South Tarawa',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇰🇮',
    emojiU: 'U+1F1F0 U+1F1EE',
  },
  {
    iso2: 'KM',
    name: 'Comoros',
    native: 'Komori',
    dialCode: '269',
    continent_name: 'AF',
    capital: 'Moroni',
    currency: 'KMF',
    languages: ['ar', 'fr'],
    emoji: '🇰🇲',
    emojiU: 'U+1F1F0 U+1F1F2',
  },
  {
    iso2: 'KN',
    name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
    dialCode: '1869',
    continent_name: 'NA',
    capital: 'Basseterre',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇰🇳',
    emojiU: 'U+1F1F0 U+1F1F3',
  },
  {
    iso2: 'KP',
    name: "Korea, Democratic People's Republic of",
    dialCode: '850',
    native: '북한',
    continent_name: 'AS',
    capital: 'Pyongyang',
    currency: 'KPW',
    languages: ['ko'],
    emoji: '🇰🇵',
    emojiU: 'U+1F1F0 U+1F1F5',
  },
  {
    iso2: 'KR',
    name: 'Korea, Republic of',
    dialCode: '82',
    native: '대한민국',
    continent_name: 'AS',
    capital: 'Seoul',
    currency: 'KRW',
    languages: ['ko'],
    emoji: '🇰🇷',
    emojiU: 'U+1F1F0 U+1F1F7',
  },
  {
    iso2: 'KW',
    name: 'Kuwait',
    native: 'الكويت',
    dialCode: '965',
    continent_name: 'AS',
    capital: 'Kuwait City',
    currency: 'KWD',
    languages: ['ar'],
    emoji: '🇰🇼',
    emojiU: 'U+1F1F0 U+1F1FC',
  },
  {
    iso2: 'KY',
    name: 'Cayman Islands',
    native: 'Cayman Islands',
    dialCode: '1345',
    continent_name: 'NA',
    capital: 'George Town',
    currency: 'KYD',
    languages: ['en'],
    emoji: '🇰🇾',
    emojiU: 'U+1F1F0 U+1F1FE',
  },
  {
    iso2: 'KZ',
    name: 'Kazakhstan',
    native: 'Қазақстан',
    dialCode: '7',
    continent_name: 'AS',
    capital: 'Astana',
    currency: 'KZT',
    languages: ['kk', 'ru'],
    emoji: '🇰🇿',
    emojiU: 'U+1F1F0 U+1F1FF',
  },
  {
    iso2: 'LA',
    name: "Lao People's Democratic Republic",
    dialCode: '856',
    native: 'ສປປລາວ',
    continent_name: 'AS',
    capital: 'Vientiane',
    currency: 'LAK',
    languages: ['lo'],
    emoji: '🇱🇦',
    emojiU: 'U+1F1F1 U+1F1E6',
  },
  {
    iso2: 'LB',
    name: 'Lebanon',
    native: 'لبنان',
    dialCode: '961',
    continent_name: 'AS',
    capital: 'Beirut',
    currency: 'LBP',
    languages: ['ar', 'fr'],
    emoji: '🇱🇧',
    emojiU: 'U+1F1F1 U+1F1E7',
  },
  {
    iso2: 'LC',
    name: 'Saint Lucia',
    native: 'Saint Lucia',
    dialCode: '1758',
    continent_name: 'NA',
    capital: 'Castries',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇱🇨',
    emojiU: 'U+1F1F1 U+1F1E8',
  },
  {
    iso2: 'LI',
    name: 'Liechtenstein',
    native: 'Liechtenstein',
    dialCode: '423',
    continent_name: 'EU',
    capital: 'Vaduz',
    currency: 'CHF',
    languages: ['de'],
    emoji: '🇱🇮',
    emojiU: 'U+1F1F1 U+1F1EE',
  },
  {
    iso2: 'LK',
    name: 'Sri Lanka',
    native: 'śrī laṃkāva',
    dialCode: '94',
    continent_name: 'AS',
    capital: 'Colombo',
    currency: 'LKR',
    languages: ['si', 'ta'],
    emoji: '🇱🇰',
    emojiU: 'U+1F1F1 U+1F1F0',
  },
  {
    iso2: 'LR',
    name: 'Liberia',
    native: 'Liberia',
    dialCode: '231',
    continent_name: 'AF',
    capital: 'Monrovia',
    currency: 'LRD',
    languages: ['en'],
    emoji: '🇱🇷',
    emojiU: 'U+1F1F1 U+1F1F7',
  },
  {
    iso2: 'LS',
    name: 'Lesotho',
    native: 'Lesotho',
    dialCode: '266',
    continent_name: 'AF',
    capital: 'Maseru',
    currency: 'LSL,ZAR',
    languages: ['en', 'st'],
    emoji: '🇱🇸',
    emojiU: 'U+1F1F1 U+1F1F8',
  },
  {
    iso2: 'LT',
    name: 'Lithuania',
    native: 'Lietuva',
    dialCode: '370',
    continent_name: 'EU',
    capital: 'Vilnius',
    currency: 'EUR',
    languages: ['lt'],
    emoji: '🇱🇹',
    emojiU: 'U+1F1F1 U+1F1F9',
  },
  {
    iso2: 'LU',
    name: 'Luxembourg',
    native: 'Luxembourg',
    dialCode: '352',
    continent_name: 'EU',
    capital: 'Luxembourg',
    currency: 'EUR',
    languages: ['fr', 'de', 'lb'],
    emoji: '🇱🇺',
    emojiU: 'U+1F1F1 U+1F1FA',
  },
  {
    iso2: 'LV',
    name: 'Latvia',
    native: 'Latvija',
    dialCode: '371',
    continent_name: 'EU',
    capital: 'Riga',
    currency: 'EUR',
    languages: ['lv'],
    emoji: '🇱🇻',
    emojiU: 'U+1F1F1 U+1F1FB',
  },
  {
    iso2: 'LY',
    name: 'Libya',
    native: '‏ليبيا',
    dialCode: '218',
    continent_name: 'AF',
    capital: 'Tripoli',
    currency: 'LYD',
    languages: ['ar'],
    emoji: '🇱🇾',
    emojiU: 'U+1F1F1 U+1F1FE',
  },
  {
    iso2: 'MA',
    name: 'Morocco',
    native: 'المغرب',
    dialCode: '212',
    continent_name: 'AF',
    capital: 'Rabat',
    currency: 'MAD',
    languages: ['ar'],
    emoji: '🇲🇦',
    emojiU: 'U+1F1F2 U+1F1E6',
  },
  {
    iso2: 'MC',
    name: 'Monaco',
    native: 'Monaco',
    dialCode: '377',
    continent_name: 'EU',
    capital: 'Monaco',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇲🇨',
    emojiU: 'U+1F1F2 U+1F1E8',
  },
  {
    iso2: 'MD',
    name: 'Moldova, Republic of',
    dialCode: '373',
    native: 'Moldova',
    continent_name: 'EU',
    capital: 'Chișinău',
    currency: 'MDL',
    languages: ['ro'],
    emoji: '🇲🇩',
    emojiU: 'U+1F1F2 U+1F1E9',
  },
  {
    iso2: 'ME',
    name: 'Montenegro',
    native: 'Црна Гора',
    dialCode: '382',
    continent_name: 'EU',
    capital: 'Podgorica',
    currency: 'EUR',
    languages: ['sr', 'bs', 'sq', 'hr'],
    emoji: '🇲🇪',
    emojiU: 'U+1F1F2 U+1F1EA',
  },
  {
    iso2: 'MF',
    name: 'Saint Martin, (French part)',
    dialCode: '590',
    native: 'Saint-Barthélemy',
    continent_name: 'NA',
    capital: 'Gustavia',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇧🇱',
    emojiU: 'U+1F1E7 U+1F1F1',
  },
  {
    iso2: 'MG',
    name: 'Madagascar',
    native: 'Madagasikara',
    dialCode: '261',
    continent_name: 'AF',
    capital: 'Antananarivo',
    currency: 'MGA',
    languages: ['fr', 'mg'],
    emoji: '🇲🇬',
    emojiU: 'U+1F1F2 U+1F1EC',
  },
  {
    iso2: 'MH',
    name: 'Marshall Islands',
    native: 'M̧ajeļ',
    dialCode: '692',
    continent_name: 'OC',
    capital: 'Majuro',
    currency: 'USD',
    languages: ['en', 'mh'],
    emoji: '🇲🇭',
    emojiU: 'U+1F1F2 U+1F1ED',
  },
  {
    iso2: 'MK',
    name: 'North Macedonia',
    native: 'Северна Македонија',
    dialCode: '389',
    continent_name: 'EU',
    capital: 'Skopje',
    currency: 'MKD',
    languages: ['mk'],
    emoji: '🇲🇰',
    emojiU: 'U+1F1F2 U+1F1F0',
  },
  {
    iso2: 'ML',
    name: 'Mali',
    native: 'Mali',
    dialCode: '223',
    continent_name: 'AF',
    capital: 'Bamako',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇲🇱',
    emojiU: 'U+1F1F2 U+1F1F1',
  },
  {
    iso2: 'MM',
    name: 'Myanmar',
    dialCode: '95',
    native: 'မြန်မာ',
    continent_name: 'AS',
    capital: 'Naypyidaw',
    currency: 'MMK',
    languages: ['my'],
    emoji: '🇲🇲',
    emojiU: 'U+1F1F2 U+1F1F2',
  },
  {
    iso2: 'MN',
    name: 'Mongolia',
    native: 'Монгол улс',
    dialCode: '976',
    continent_name: 'AS',
    capital: 'Ulan Bator',
    currency: 'MNT',
    languages: ['mn'],
    emoji: '🇲🇳',
    emojiU: 'U+1F1F2 U+1F1F3',
  },
  {
    iso2: 'MO',
    name: 'Macao',
    native: '澳門',
    dialCode: '853',
    continent_name: 'AS',
    capital: '',
    currency: 'MOP',
    languages: ['zh', 'pt'],
    emoji: '🇲🇴',
    emojiU: 'U+1F1F2 U+1F1F4',
  },
  {
    iso2: 'MP',
    name: 'Northern Mariana Islands',
    native: 'Northern Mariana Islands',
    dialCode: '1670',
    continent_name: 'OC',
    capital: 'Saipan',
    currency: 'USD',
    languages: ['en', 'ch'],
    emoji: '🇲🇵',
    emojiU: 'U+1F1F2 U+1F1F5',
  },
  {
    iso2: 'MQ',
    name: 'Martinique',
    native: 'Martinique',
    dialCode: '596',
    continent_name: 'NA',
    capital: 'Fort-de-France',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇲🇶',
    emojiU: 'U+1F1F2 U+1F1F6',
  },
  {
    iso2: 'MR',
    name: 'Mauritania',
    native: 'موريتانيا',
    dialCode: '222',
    continent_name: 'AF',
    capital: 'Nouakchott',
    currency: 'MRU',
    languages: ['ar'],
    emoji: '🇲🇷',
    emojiU: 'U+1F1F2 U+1F1F7',
  },
  {
    iso2: 'MS',
    name: 'Montserrat',
    native: 'Montserrat',
    dialCode: '1664',
    continent_name: 'NA',
    capital: 'Plymouth',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇲🇸',
    emojiU: 'U+1F1F2 U+1F1F8',
  },
  {
    iso2: 'MT',
    name: 'Malta',
    native: 'Malta',
    dialCode: '356',
    continent_name: 'EU',
    capital: 'Valletta',
    currency: 'EUR',
    languages: ['mt', 'en'],
    emoji: '🇲🇹',
    emojiU: 'U+1F1F2 U+1F1F9',
  },
  {
    iso2: 'MU',
    name: 'Mauritius',
    native: 'Maurice',
    dialCode: '230',
    continent_name: 'AF',
    capital: 'Port Louis',
    currency: 'MUR',
    languages: ['en'],
    emoji: '🇲🇺',
    emojiU: 'U+1F1F2 U+1F1FA',
  },
  {
    iso2: 'MV',
    name: 'Maldives',
    native: 'Maldives',
    dialCode: '960',
    continent_name: 'AS',
    capital: 'Malé',
    currency: 'MVR',
    languages: ['dv'],
    emoji: '🇲🇻',
    emojiU: 'U+1F1F2 U+1F1FB',
  },
  {
    iso2: 'MW',
    name: 'Malawi',
    native: 'Malawi',
    dialCode: '265',
    continent_name: 'AF',
    capital: 'Lilongwe',
    currency: 'MWK',
    languages: ['en', 'ny'],
    emoji: '🇲🇼',
    emojiU: 'U+1F1F2 U+1F1FC',
  },
  {
    iso2: 'MX',
    name: 'Mexico',
    native: 'México',
    dialCode: '52',
    continent_name: 'NA',
    capital: 'Mexico City',
    currency: 'MXN',
    languages: ['es'],
    emoji: '🇲🇽',
    emojiU: 'U+1F1F2 U+1F1FD',
  },
  {
    iso2: 'MY',
    name: 'Malaysia',
    native: 'Malaysia',
    dialCode: '60',
    continent_name: 'AS',
    capital: 'Kuala Lumpur',
    currency: 'MYR',
    languages: ['ms'],
    emoji: '🇲🇾',
    emojiU: 'U+1F1F2 U+1F1FE',
  },
  {
    iso2: 'MZ',
    name: 'Mozambique',
    native: 'Moçambique',
    dialCode: '258',
    continent_name: 'AF',
    capital: 'Maputo',
    currency: 'MZN',
    languages: ['pt'],
    emoji: '🇲🇿',
    emojiU: 'U+1F1F2 U+1F1FF',
  },
  {
    iso2: 'NA',
    name: 'Namibia',
    native: 'Namibia',
    dialCode: '264',
    continent_name: 'AF',
    capital: 'Windhoek',
    currency: 'NAD,ZAR',
    languages: ['en', 'af'],
    emoji: '🇳🇦',
    emojiU: 'U+1F1F3 U+1F1E6',
  },
  {
    iso2: 'NC',
    name: 'New Caledonia',
    native: 'Nouvelle-Calédonie',
    dialCode: '687',
    continent_name: 'OC',
    capital: 'Nouméa',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇳🇨',
    emojiU: 'U+1F1F3 U+1F1E8',
  },
  {
    iso2: 'NE',
    name: 'Niger',
    native: 'Niger',
    dialCode: '227',
    continent_name: 'AF',
    capital: 'Niamey',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇳🇪',
    emojiU: 'U+1F1F3 U+1F1EA',
  },
  {
    iso2: 'NF',
    name: 'Norfolk Island',
    native: 'Norfolk Island',
    dialCode: '672',
    continent_name: 'OC',
    capital: 'Kingston',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇳🇫',
    emojiU: 'U+1F1F3 U+1F1EB',
  },
  {
    iso2: 'NG',
    name: 'Nigeria',
    native: 'Nigeria',
    dialCode: '234',
    continent_name: 'AF',
    capital: 'Abuja',
    currency: 'NGN',
    languages: ['en'],
    emoji: '🇳🇬',
    emojiU: 'U+1F1F3 U+1F1EC',
  },
  {
    iso2: 'NI',
    name: 'Nicaragua',
    native: 'Nicaragua',
    dialCode: '505',
    continent_name: 'NA',
    capital: 'Managua',
    currency: 'NIO',
    languages: ['es'],
    emoji: '🇳🇮',
    emojiU: 'U+1F1F3 U+1F1EE',
  },
  {
    iso2: 'NL',
    name: 'Netherlands',
    native: 'Nederland',
    dialCode: '31',
    continent_name: 'EU',
    capital: 'Amsterdam',
    currency: 'EUR',
    languages: ['nl'],
    emoji: '🇳🇱',
    emojiU: 'U+1F1F3 U+1F1F1',
  },
  {
    iso2: 'NO',
    name: 'Norway',
    native: 'Norge',
    dialCode: '47',
    continent_name: 'EU',
    capital: 'Oslo',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇳🇴',
    emojiU: 'U+1F1F3 U+1F1F4',
  },
  {
    iso2: 'NP',
    name: 'Nepal',
    native: 'नपल',
    dialCode: '977',
    continent_name: 'AS',
    capital: 'Kathmandu',
    currency: 'NPR',
    languages: ['ne'],
    emoji: '🇳🇵',
    emojiU: 'U+1F1F3 U+1F1F5',
  },
  {
    iso2: 'NR',
    name: 'Nauru',
    native: 'Nauru',
    dialCode: '674',
    continent_name: 'OC',
    capital: 'Yaren',
    currency: 'AUD',
    languages: ['en', 'na'],
    emoji: '🇳🇷',
    emojiU: 'U+1F1F3 U+1F1F7',
  },
  {
    iso2: 'NU',
    name: 'Niue',
    native: 'Niuē',
    dialCode: '683',
    continent_name: 'OC',
    capital: 'Alofi',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇳🇺',
    emojiU: 'U+1F1F3 U+1F1FA',
  },
  {
    iso2: 'NZ',
    name: 'New Zealand',
    native: 'New Zealand',
    dialCode: '64',
    continent_name: 'OC',
    capital: 'Wellington',
    currency: 'NZD',
    languages: ['en', 'mi'],
    emoji: '🇳🇿',
    emojiU: 'U+1F1F3 U+1F1FF',
  },
  {
    iso2: 'OM',
    name: 'Oman',
    native: 'عمان',
    dialCode: '968',
    continent_name: 'AS',
    capital: 'Muscat',
    currency: 'OMR',
    languages: ['ar'],
    emoji: '🇴🇲',
    emojiU: 'U+1F1F4 U+1F1F2',
  },
  {
    iso2: 'PA',
    name: 'Panama',
    native: 'Panamá',
    dialCode: '507',
    continent_name: 'NA',
    capital: 'Panama City',
    currency: 'PAB,USD',
    languages: ['es'],
    emoji: '🇵🇦',
    emojiU: 'U+1F1F5 U+1F1E6',
  },
  {
    iso2: 'PE',
    name: 'Peru',
    native: 'Perú',
    dialCode: '51',
    continent_name: 'SA',
    capital: 'Lima',
    currency: 'PEN',
    languages: ['es'],
    emoji: '🇵🇪',
    emojiU: 'U+1F1F5 U+1F1EA',
  },
  {
    iso2: 'PF',
    name: 'French Polynesia',
    native: 'Polynésie française',
    dialCode: '689',
    continent_name: 'OC',
    capital: 'Papeetē',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇵🇫',
    emojiU: 'U+1F1F5 U+1F1EB',
  },
  {
    iso2: 'PG',
    name: 'Papua New Guinea',
    native: 'Papua Niugini',
    dialCode: '675',
    continent_name: 'OC',
    capital: 'Port Moresby',
    currency: 'PGK',
    languages: ['en'],
    emoji: '🇵🇬',
    emojiU: 'U+1F1F5 U+1F1EC',
  },
  {
    iso2: 'PH',
    name: 'Philippines',
    native: 'Pilipinas',
    dialCode: '63',
    continent_name: 'AS',
    capital: 'Manila',
    currency: 'PHP',
    languages: ['en'],
    emoji: '🇵🇭',
    emojiU: 'U+1F1F5 U+1F1ED',
  },
  {
    iso2: 'PK',
    name: 'Pakistan',
    native: 'Pakistan',
    dialCode: '92',
    continent_name: 'AS',
    capital: 'Islamabad',
    currency: 'PKR',
    languages: ['en', 'ur'],
    emoji: '🇵🇰',
    emojiU: 'U+1F1F5 U+1F1F0',
  },
  {
    iso2: 'PL',
    name: 'Poland',
    native: 'Polska',
    dialCode: '48',
    continent_name: 'EU',
    capital: 'Warsaw',
    currency: 'PLN',
    languages: ['pl'],
    emoji: '🇵🇱',
    emojiU: 'U+1F1F5 U+1F1F1',
  },
  {
    iso2: 'PM',
    name: 'Saint Pierre and Miquelon',
    native: 'Saint-Pierre-et-Miquelon',
    dialCode: '508',
    continent_name: 'NA',
    capital: 'Saint-Pierre',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇵🇲',
    emojiU: 'U+1F1F5 U+1F1F2',
  },
  {
    iso2: 'PN',
    name: 'Pitcairn',
    dialCode: '64',
    native: 'Pitcairn Islands',
    continent_name: 'OC',
    capital: 'Adamstown',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇵🇳',
    emojiU: 'U+1F1F5 U+1F1F3',
    invalid: true,
  },
  {
    iso2: 'AS',
    name: 'American Samoa',
    native: 'American Samoa',
    dialCode: '1',
    continent_name: 'OC',
    capital: 'Pago Pago',
    currency: 'USD',
    languages: ['en', 'sm'],
    emoji: '🇦🇸',
    emojiU: 'U+1F1E6 U+1F1F8',
  },
  {
    iso2: 'PS',
    name: 'Palestine, State of',
    dialCode: '970',
    native: 'فلسطين',
    continent_name: 'AS',
    capital: 'Ramallah',
    currency: 'ILS',
    languages: ['ar'],
    emoji: '🇵🇸',
    emojiU: 'U+1F1F5 U+1F1F8',
  },
  {
    iso2: 'PT',
    name: 'Portugal',
    native: 'Portugal',
    dialCode: '351',
    continent_name: 'EU',
    capital: 'Lisbon',
    currency: 'EUR',
    languages: ['pt'],
    emoji: '🇵🇹',
    emojiU: 'U+1F1F5 U+1F1F9',
  },
  {
    iso2: 'PW',
    name: 'Palau',
    native: 'Palau',
    dialCode: '680',
    continent_name: 'OC',
    capital: 'Ngerulmud',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇵🇼',
    emojiU: 'U+1F1F5 U+1F1FC',
  },
  {
    iso2: 'PY',
    name: 'Paraguay',
    native: 'Paraguay',
    dialCode: '595',
    continent_name: 'SA',
    capital: 'Asunción',
    currency: 'PYG',
    languages: ['es', 'gn'],
    emoji: '🇵🇾',
    emojiU: 'U+1F1F5 U+1F1FE',
  },
  {
    iso2: 'QA',
    name: 'Qatar',
    native: 'قطر',
    dialCode: '974',
    continent_name: 'AS',
    capital: 'Doha',
    currency: 'QAR',
    languages: ['ar'],
    emoji: '🇶🇦',
    emojiU: 'U+1F1F6 U+1F1E6',
  },
  {
    iso2: 'RE',
    name: 'Réunion',
    native: 'La Réunion',
    dialCode: '262',
    continent_name: 'AF',
    capital: 'Saint-Denis',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇷🇪',
    emojiU: 'U+1F1F7 U+1F1EA',
  },
  {
    iso2: 'RO',
    name: 'Romania',
    native: 'România',
    dialCode: '40',
    continent_name: 'EU',
    capital: 'Bucharest',
    currency: 'RON',
    languages: ['ro'],
    emoji: '🇷🇴',
    emojiU: 'U+1F1F7 U+1F1F4',
  },
  {
    iso2: 'RS',
    name: 'Serbia',
    native: 'Србија',
    dialCode: '381',
    continent_name: 'EU',
    capital: 'Belgrade',
    currency: 'RSD',
    languages: ['sr'],
    emoji: '🇷🇸',
    emojiU: 'U+1F1F7 U+1F1F8',
  },
  {
    iso2: 'RU',
    name: 'Russian Federation',
    dialCode: '7',
    native: 'Россия',
    continent_name: 'EU',
    capital: 'Moscow',
    currency: 'RUB',
    languages: ['ru'],
    emoji: '🇷🇺',
    emojiU: 'U+1F1F7 U+1F1FA',
  },
  {
    iso2: 'RW',
    name: 'Rwanda',
    native: 'Rwanda',
    dialCode: '250',
    continent_name: 'AF',
    capital: 'Kigali',
    currency: 'RWF',
    languages: ['rw', 'en', 'fr'],
    emoji: '🇷🇼',
    emojiU: 'U+1F1F7 U+1F1FC',
  },
  {
    iso2: 'SA',
    name: 'Saudi Arabia',
    native: 'العربية السعودية',
    dialCode: '966',
    continent_name: 'AS',
    capital: 'Riyadh',
    currency: 'SAR',
    languages: ['ar'],
    emoji: '🇸🇦',
    emojiU: 'U+1F1F8 U+1F1E6',
  },
  {
    iso2: 'SB',
    name: 'Solomon Islands',
    native: 'Solomon Islands',
    dialCode: '677',
    continent_name: 'OC',
    capital: 'Honiara',
    currency: 'SBD',
    languages: ['en'],
    emoji: '🇸🇧',
    emojiU: 'U+1F1F8 U+1F1E7',
  },
  {
    iso2: 'SC',
    name: 'Seychelles',
    native: 'Seychelles',
    dialCode: '248',
    continent_name: 'AF',
    capital: 'Victoria',
    currency: 'SCR',
    languages: ['fr', 'en'],
    emoji: '🇸🇨',
    emojiU: 'U+1F1F8 U+1F1E8',
  },
  {
    iso2: 'SD',
    name: 'Sudan',
    native: 'السودان',
    dialCode: '249',
    continent_name: 'AF',
    capital: 'Khartoum',
    currency: 'SDG',
    languages: ['ar', 'en'],
    emoji: '🇸🇩',
    emojiU: 'U+1F1F8 U+1F1E9',
  },
  {
    iso2: 'SE',
    name: 'Sweden',
    native: 'Sverige',
    dialCode: '46',
    continent_name: 'EU',
    capital: 'Stockholm',
    currency: 'SEK',
    languages: ['sv'],
    emoji: '🇸🇪',
    emojiU: 'U+1F1F8 U+1F1EA',
  },
  {
    iso2: 'SG',
    name: 'Singapore',
    native: 'Singapore',
    dialCode: '65',
    continent_name: 'AS',
    capital: 'Singapore',
    currency: 'SGD',
    languages: ['en', 'ms', 'ta', 'zh'],
    emoji: '🇸🇬',
    emojiU: 'U+1F1F8 U+1F1EC',
  },
  {
    iso2: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    dialCode: '290',
    native: 'Saint Helena',
    continent_name: 'AF',
    capital: 'Jamestown',
    currency: 'SHP',
    languages: ['en'],
    emoji: '🇸🇭',
    emojiU: 'U+1F1F8 U+1F1ED',
  },
  {
    iso2: 'SI',
    name: 'Slovenia',
    native: 'Slovenija',
    dialCode: '386',
    continent_name: 'EU',
    capital: 'Ljubljana',
    currency: 'EUR',
    languages: ['sl'],
    emoji: '🇸🇮',
    emojiU: 'U+1F1F8 U+1F1EE',
  },
  {
    iso2: 'SJ',
    name: 'Svalbard and Jan Mayen',
    native: 'Svalbard og Jan Mayen',
    dialCode: '47',
    continent_name: 'EU',
    capital: 'Longyearbyen',
    currency: 'NOK',
    languages: ['no'],
    emoji: '🇸🇯',
    emojiU: 'U+1F1F8 U+1F1EF',
  },
  {
    iso2: 'SK',
    name: 'Slovakia',
    native: 'Slovensko',
    dialCode: '421',
    continent_name: 'EU',
    capital: 'Bratislava',
    currency: 'EUR',
    languages: ['sk'],
    emoji: '🇸🇰',
    emojiU: 'U+1F1F8 U+1F1F0',
  },
  {
    iso2: 'SL',
    name: 'Sierra Leone',
    native: 'Sierra Leone',
    dialCode: '232',
    continent_name: 'AF',
    capital: 'Freetown',
    currency: 'SLL',
    languages: ['en'],
    emoji: '🇸🇱',
    emojiU: 'U+1F1F8 U+1F1F1',
  },
  {
    iso2: 'SM',
    name: 'San Marino',
    native: 'San Marino',
    dialCode: '378',
    continent_name: 'EU',
    capital: 'City of San Marino',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇸🇲',
    emojiU: 'U+1F1F8 U+1F1F2',
  },
  {
    iso2: 'SN',
    name: 'Senegal',
    native: 'Sénégal',
    dialCode: '221',
    continent_name: 'AF',
    capital: 'Dakar',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇸🇳',
    emojiU: 'U+1F1F8 U+1F1F3',
  },
  {
    iso2: 'SO',
    name: 'Somalia',
    native: 'Soomaaliya',
    dialCode: '252',
    continent_name: 'AF',
    capital: 'Mogadishu',
    currency: 'SOS',
    languages: ['so', 'ar'],
    emoji: '🇸🇴',
    emojiU: 'U+1F1F8 U+1F1F4',
  },
  {
    iso2: 'SR',
    name: 'Suriname',
    dialCode: '597',
    native: 'Suricountry_name',
    continent_name: 'SA',
    capital: 'Paramaribo',
    currency: 'SRD',
    languages: ['nl'],
    emoji: '🇸🇷',
    emojiU: 'U+1F1F8 U+1F1F7',
  },
  {
    iso2: 'SS',
    name: 'South Sudan',
    native: 'South Sudan',
    dialCode: '211',
    continent_name: 'AF',
    capital: 'Juba',
    currency: 'SSP',
    languages: ['en'],
    emoji: '🇸🇸',
    emojiU: 'U+1F1F8 U+1F1F8',
  },
  {
    iso2: 'ST',
    name: 'Sao Tome and Principe',
    dialCode: '239',
    native: 'São Tomé e Príncipe',
    continent_name: 'AF',
    capital: 'São Tomé',
    currency: 'STN',
    languages: ['pt'],
    emoji: '🇸🇹',
    emojiU: 'U+1F1F8 U+1F1F9',
  },
  {
    iso2: 'SV',
    name: 'El Salvador',
    native: 'El Salvador',
    dialCode: '503',
    continent_name: 'NA',
    capital: 'San Salvador',
    currency: 'SVC,USD',
    languages: ['es'],
    emoji: '🇸🇻',
    emojiU: 'U+1F1F8 U+1F1FB',
  },
  {
    iso2: 'SX',
    name: 'Sint Maarten, (Dutch part)',
    dialCode: '1721',
    native: 'Sint Maarten',
    continent_name: 'NA',
    capital: 'Philipsburg',
    currency: 'ANG',
    languages: ['nl', 'en'],
    emoji: '🇸🇽',
    emojiU: 'U+1F1F8 U+1F1FD',
  },
  {
    iso2: 'SY',
    name: 'Syrian Arab Republic',
    dialCode: '963',
    native: 'سوريا',
    continent_name: 'AS',
    capital: 'Damascus',
    currency: 'SYP',
    languages: ['ar'],
    emoji: '🇸🇾',
    emojiU: 'U+1F1F8 U+1F1FE',
  },
  {
    iso2: 'SZ',
    name: 'Eswatini',
    dialCode: '268',
    native: 'Swaziland',
    continent_name: 'AF',
    capital: 'Lobamba',
    currency: 'SZL',
    languages: ['en', 'ss'],
    emoji: '🇸🇿',
    emojiU: 'U+1F1F8 U+1F1FF',
  },
  {
    iso2: 'TC',
    name: 'Turks and Caicos Islands',
    native: 'Turks and Caicos Islands',
    dialCode: '1649',
    continent_name: 'NA',
    capital: 'Cockburn Town',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇹🇨',
    emojiU: 'U+1F1F9 U+1F1E8',
  },
  {
    iso2: 'TD',
    name: 'Chad',
    native: 'Tchad',
    dialCode: '235',
    continent_name: 'AF',
    capital: "N'Djamena",
    currency: 'XAF',
    languages: ['fr', 'ar'],
    emoji: '🇹🇩',
    emojiU: 'U+1F1F9 U+1F1E9',
  },
  {
    iso2: 'TF',
    name: 'French Southern Territories',
    native: 'Territoire des Terres australes et antarctiques fr',
    dialCode: '262',
    continent_name: 'AN',
    capital: 'Port-aux-Français',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇹🇫',
    emojiU: 'U+1F1F9 U+1F1EB',
    invalid: true,
  },
  {
    iso2: 'TG',
    name: 'Togo',
    native: 'Togo',
    dialCode: '228',
    continent_name: 'AF',
    capital: 'Lomé',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇹🇬',
    emojiU: 'U+1F1F9 U+1F1EC',
  },
  {
    iso2: 'TH',
    name: 'Thailand',
    native: 'ประเทศไทย',
    dialCode: '66',
    continent_name: 'AS',
    capital: 'Bangkok',
    currency: 'THB',
    languages: ['th'],
    emoji: '🇹🇭',
    emojiU: 'U+1F1F9 U+1F1ED',
  },
  {
    iso2: 'TJ',
    name: 'Tajikistan',
    native: 'Тоҷикистон',
    dialCode: '992',
    continent_name: 'AS',
    capital: 'Dushanbe',
    currency: 'TJS',
    languages: ['tg', 'ru'],
    emoji: '🇹🇯',
    emojiU: 'U+1F1F9 U+1F1EF',
  },
  {
    iso2: 'TK',
    name: 'Tokelau',
    native: 'Tokelau',
    dialCode: '690',
    continent_name: 'OC',
    capital: 'Fakaofo',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇹🇰',
    emojiU: 'U+1F1F9 U+1F1F0',
  },
  {
    iso2: 'TL',
    name: 'Timor-Leste',
    dialCode: '670',
    native: 'Timor-Leste',
    continent_name: 'OC',
    capital: 'Dili',
    currency: 'USD',
    languages: ['pt'],
    emoji: '🇹🇱',
    emojiU: 'U+1F1F9 U+1F1F1',
  },
  {
    iso2: 'TM',
    name: 'Turkmenistan',
    native: 'Türkmenistan',
    dialCode: '993',
    continent_name: 'AS',
    capital: 'Ashgabat',
    currency: 'TMT',
    languages: ['tk', 'ru'],
    emoji: '🇹🇲',
    emojiU: 'U+1F1F9 U+1F1F2',
  },
  {
    iso2: 'TN',
    name: 'Tunisia',
    native: 'تونس',
    dialCode: '216',
    continent_name: 'AF',
    capital: 'Tunis',
    currency: 'TND',
    languages: ['ar'],
    emoji: '🇹🇳',
    emojiU: 'U+1F1F9 U+1F1F3',
  },
  {
    iso2: 'TO',
    name: 'Tonga',
    native: 'Tonga',
    dialCode: '676',
    continent_name: 'OC',
    capital: "Nuku'alofa",
    currency: 'TOP',
    languages: ['en', 'to'],
    emoji: '🇹🇴',
    emojiU: 'U+1F1F9 U+1F1F4',
  },
  {
    iso2: 'TR',
    name: 'Turkey',
    native: 'Türkiye',
    dialCode: '90',
    continent_name: 'AS',
    capital: 'Ankara',
    currency: 'TRY',
    languages: ['tr'],
    emoji: '🇹🇷',
    emojiU: 'U+1F1F9 U+1F1F7',
  },
  {
    iso2: 'TT',
    name: 'Trinidad and Tobago',
    native: 'Trinidad and Tobago',
    dialCode: '1868',
    continent_name: 'NA',
    capital: 'Port of Spain',
    currency: 'TTD',
    languages: ['en'],
    emoji: '🇹🇹',
    emojiU: 'U+1F1F9 U+1F1F9',
  },
  {
    iso2: 'TV',
    name: 'Tuvalu',
    native: 'Tuvalu',
    dialCode: '688',
    continent_name: 'OC',
    capital: 'Funafuti',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇹🇻',
    emojiU: 'U+1F1F9 U+1F1FB',
  },
  {
    iso2: 'TW',
    name: 'Taiwan, Province of China',
    dialCode: '886',
    native: '臺灣',
    continent_name: 'AS',
    capital: 'Taipei',
    currency: 'TWD',
    languages: ['zh'],
    emoji: '🇹🇼',
    emojiU: 'U+1F1F9 U+1F1FC',
  },
  {
    iso2: 'TZ',
    name: 'Tanzania, United Republic of',
    dialCode: '255',
    native: 'Tanzania',
    continent_name: 'AF',
    capital: 'Dodoma',
    currency: 'TZS',
    languages: ['sw', 'en'],
    emoji: '🇹🇿',
    emojiU: 'U+1F1F9 U+1F1FF',
  },
  {
    iso2: 'UA',
    name: 'Ukraine',
    native: 'Україна',
    dialCode: '380',
    continent_name: 'EU',
    capital: 'Kyiv',
    currency: 'UAH',
    languages: ['uk'],
    emoji: '🇺🇦',
    emojiU: 'U+1F1FA U+1F1E6',
  },
  {
    iso2: 'UG',
    name: 'Uganda',
    native: 'Uganda',
    dialCode: '256',
    continent_name: 'AF',
    capital: 'Kampala',
    currency: 'UGX',
    languages: ['en', 'sw'],
    emoji: '🇺🇬',
    emojiU: 'U+1F1FA U+1F1EC',
  },
  {
    iso2: 'BB',
    name: 'Barbados',
    native: 'Barbados',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'Bridgetown',
    currency: 'BBD',
    languages: ['en'],
    emoji: '🇧🇧',
    emojiU: 'U+1F1E7 U+1F1E7',
  },
  {
    iso2: 'BS',
    name: 'Bahamas',
    native: 'Bahamas',
    dialCode: '1',
    continent_name: 'NA',
    capital: 'Nassau',
    currency: 'BSD',
    languages: ['en'],
    emoji: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
  },
  {
    iso2: 'UY',
    name: 'Uruguay',
    native: 'Uruguay',
    dialCode: '598',
    continent_name: 'SA',
    capital: 'Montevideo',
    currency: 'UYI,UYU',
    languages: ['es'],
    emoji: '🇺🇾',
    emojiU: 'U+1F1FA U+1F1FE',
  },
  {
    iso2: 'UZ',
    name: 'Uzbekistan',
    native: 'O‘zbekiston',
    dialCode: '998',
    continent_name: 'AS',
    capital: 'Tashkent',
    currency: 'UZS',
    languages: ['uz', 'ru'],
    emoji: '🇺🇿',
    emojiU: 'U+1F1FA U+1F1FF',
  },
  {
    iso2: 'VA',
    name: 'Holy See',
    dialCode: '39',
    native: 'Italia',
    continent_name: 'EU',
    capital: 'Rome',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇮🇹',
    emojiU: 'U+1F1EE U+1F1F9',
  },
  {
    iso2: 'VC',
    name: 'Saint Vincent and the Grenadines',
    native: 'Saint Vincent and the Grenadines',
    dialCode: '1784',
    continent_name: 'NA',
    capital: 'Kingstown',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇻🇨',
    emojiU: 'U+1F1FB U+1F1E8',
  },
  {
    iso2: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    dialCode: '58',
    native: 'Venezuela',
    continent_name: 'SA',
    capital: 'Caracas',
    currency: 'VES',
    languages: ['es'],
    emoji: '🇻🇪',
    emojiU: 'U+1F1FB U+1F1EA',
  },
  {
    iso2: 'VG',
    name: 'Virgin Islands, British',
    dialCode: '1284',
    native: 'British Virgin Islands',
    continent_name: 'NA',
    capital: 'Road Town',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇬',
    emojiU: 'U+1F1FB U+1F1EC',
  },
  {
    iso2: 'VI',
    name: 'Virgin Islands, U.S.',
    dialCode: '1340',
    native: 'United States Virgin Islands',
    continent_name: 'NA',
    capital: 'Charlotte Amalie',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇮',
    emojiU: 'U+1F1FB U+1F1EE',
  },
  {
    iso2: 'VN',
    name: 'Viet Nam',
    dialCode: '84',
    native: 'Việt Nam',
    continent_name: 'AS',
    capital: 'Hanoi',
    currency: 'VND',
    languages: ['vi'],
    emoji: '🇻🇳',
    emojiU: 'U+1F1FB U+1F1F3',
  },
  {
    iso2: 'VU',
    name: 'Vanuatu',
    native: 'Vanuatu',
    dialCode: '678',
    continent_name: 'OC',
    capital: 'Port Vila',
    currency: 'VUV',
    languages: ['bi', 'en', 'fr'],
    emoji: '🇻🇺',
    emojiU: 'U+1F1FB U+1F1FA',
  },
  {
    iso2: 'WF',
    name: 'Wallis and Futuna',
    native: 'Wallis et Futuna',
    dialCode: '681',
    continent_name: 'OC',
    capital: 'Mata-Utu',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇼🇫',
    emojiU: 'U+1F1FC U+1F1EB',
  },
  {
    iso2: 'WS',
    name: 'Samoa',
    native: 'Samoa',
    dialCode: '685',
    continent_name: 'OC',
    capital: 'Apia',
    currency: 'WST',
    languages: ['sm', 'en'],
    emoji: '🇼🇸',
    emojiU: 'U+1F1FC U+1F1F8',
  },
  {
    iso2: 'YE',
    name: 'Yemen',
    native: 'اليَمَن',
    dialCode: '967',
    continent_name: 'AS',
    capital: "Sana'a",
    currency: 'YER',
    languages: ['ar'],
    emoji: '🇾🇪',
    emojiU: 'U+1F1FE U+1F1EA',
  },
  {
    iso2: 'YT',
    name: 'Mayotte',
    native: 'Mayotte',
    dialCode: '262',
    continent_name: 'AF',
    capital: 'Mamoudzou',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇾🇹',
    emojiU: 'U+1F1FE U+1F1F9',
  },
  {
    iso2: 'ZA',
    name: 'South Africa',
    native: 'South Africa',
    dialCode: '27',
    continent_name: 'AF',
    capital: 'Pretoria',
    currency: 'ZAR',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
    emoji: '🇿🇦',
    emojiU: 'U+1F1FF U+1F1E6',
  },
  {
    iso2: 'ZM',
    name: 'Zambia',
    native: 'Zambia',
    dialCode: '260',
    continent_name: 'AF',
    capital: 'Lusaka',
    currency: 'ZMW',
    languages: ['en'],
    emoji: '🇿🇲',
    emojiU: 'U+1F1FF U+1F1F2',
  },
  {
    iso2: 'ZW',
    name: 'Zimbabwe',
    native: 'Zimbabwe',
    dialCode: '263',
    continent_name: 'AF',
    capital: 'Harare',
    currency: 'USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY',
    languages: ['en', 'sn', 'nd'],
    emoji: '🇿🇼',
    emojiU: 'U+1F1FF U+1F1FC',
  },
].filter(f => !f.invalid);

export const languageInformation = [
  { code: 'aa', name: 'Afar' },
  { code: 'ab', name: 'Abkhazian' },
  { code: 'ae', name: 'Avestan' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'ak', name: 'Akan' },
  { code: 'am', name: 'Amharic' },
  { code: 'an', name: 'Aragonese' },
  { code: 'ar', name: 'Arabic' },
  { code: 'as', name: 'Assamese' },
  { code: 'av', name: 'Avaric' },
  { code: 'ay', name: 'Aymara' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'ba', name: 'Bashkir' },
  { code: 'be', name: 'Belarusian' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'bh', name: 'Bihari languages' },
  { code: 'bi', name: 'Bislama' },
  { code: 'bm', name: 'Bambara' },
  { code: 'bn', name: 'Bengali' },
  { code: 'bo', name: 'Tibetan' },
  { code: 'br', name: 'Breton' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'ca', name: 'Catalan; Valencian' },
  { code: 'ce', name: 'Chechen' },
  { code: 'ch', name: 'Chamorro' },
  { code: 'co', name: 'Corsican' },
  { code: 'cr', name: 'Cree' },
  { code: 'cs', name: 'Czech' },
  {
    code: 'cu',
    name: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
  },
  { code: 'cv', name: 'Chuvash' },
  { code: 'cy', name: 'Welsh' },
  { code: 'da', name: 'Danish' },
  { code: 'de', name: 'German' },
  { code: 'dv', name: 'Divehi; Dhivehi; Maldivian' },
  { code: 'dz', name: 'Dzongkha' },
  { code: 'ee', name: 'Ewe' },
  { code: 'el', name: 'Greek, Modern (1453-)' },
  { code: 'en', name: 'English' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'es', name: 'Spanish; Castilian' },
  { code: 'et', name: 'Estonian' },
  { code: 'eu', name: 'Basque' },
  { code: 'fa', name: 'Persian' },
  { code: 'ff', name: 'Fulah' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fj', name: 'Fijian' },
  { code: 'fo', name: 'Faroese' },
  { code: 'fr', name: 'French' },
  { code: 'fy', name: 'Western Frisian' },
  { code: 'ga', name: 'Irish' },
  { code: 'gd', name: 'Gaelic; Scomttish Gaelic' },
  { code: 'gl', name: 'Galician' },
  { code: 'gn', name: 'Guarani' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'gv', name: 'Manx' },
  { code: 'ha', name: 'Hausa' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ho', name: 'Hiri Motu' },
  { code: 'hr', name: 'Croatian' },
  { code: 'ht', name: 'Haitian; Haitian Creole' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'hz', name: 'Herero' },
  {
    code: 'ia',
    name: 'Interlingua (International Auxiliary Language Association)',
  },
  { code: 'id', name: 'Indonesian' },
  { code: 'ie', name: 'Interlingue; Occidental' },
  { code: 'ig', name: 'Igbo' },
  { code: 'ii', name: 'Sichuan Yi; Nuosu' },
  { code: 'ik', name: 'Inupiaq' },
  { code: 'io', name: 'Ido' },
  { code: 'is', name: 'Icelandic' },
  { code: 'it', name: 'Italian' },
  { code: 'iu', name: 'Inuktitut' },
  { code: 'ja', name: 'Japanese' },
  { code: 'jv', name: 'Javanese' },
  { code: 'ka', name: 'Georgian' },
  { code: 'kg', name: 'Kongo' },
  { code: 'ki', name: 'Kikuyu; Gikuyu' },
  { code: 'kj', name: 'Kuanyama; Kwanyama' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'kl', name: 'Kalaallisut; Greenlandic' },
  { code: 'km', name: 'Central Khmer' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ko', name: 'Korean' },
  { code: 'kr', name: 'Kanuri' },
  { code: 'ks', name: 'Kashmiri' },
  { code: 'ku', name: 'Kurdish' },
  { code: 'kv', name: 'Komi' },
  { code: 'kw', name: 'Cornish' },
  { code: 'ky', name: 'Kirghiz; Kyrgyz' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Luxembourgish; Letzeburgesch' },
  { code: 'lg', name: 'Ganda' },
  { code: 'li', name: 'Limburgan; Limburger; Limburgish' },
  { code: 'ln', name: 'Lingala' },
  { code: 'lo', name: 'Lao' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lu', name: 'Luba-Katanga' },
  { code: 'lv', name: 'Latvian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'mh', name: 'Marshallese' },
  { code: 'mi', name: 'Maori' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ms', name: 'Malay' },
  { code: 'mt', name: 'Maltese' },
  { code: 'my', name: 'Burmese' },
  { code: 'na', name: 'Nauru' },
  {
    code: 'nb',
    name: 'Bokmål, Norwegian; Norwegian Bokmål',
  },
  { code: 'nd', name: 'Ndebele, North; North Ndebele' },
  { code: 'ne', name: 'Nepali' },
  { code: 'ng', name: 'Ndonga' },
  { code: 'nl', name: 'Dutch; Flemish' },
  { code: 'nn', name: 'Norwegian Nynorsk; Nynorsk, Norwegian' },
  { code: 'no', name: 'Norwegian' },
  { code: 'nr', name: 'Ndebele, South; South Ndebele' },
  { code: 'nv', name: 'Navajo; Navaho' },
  { code: 'ny', name: 'Chichewa; Chewa; Nyanja' },
  { code: 'oc', name: 'Occitan (post 1500)' },
  { code: 'oj', name: 'Ojibwa' },
  { code: 'om', name: 'Oromo' },
  { code: 'or', name: 'Oriya' },
  { code: 'os', name: 'Ossetian; Ossetic' },
  { code: 'pa', name: 'Panjabi; Punjabi' },
  { code: 'pi', name: 'Pali' },
  { code: 'pl', name: 'Polish' },
  { code: 'ps', name: 'Pushto; Pashto' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'qu', name: 'Quechua' },
  { code: 'rm', name: 'Romansh' },
  { code: 'rn', name: 'Rundi' },
  { code: 'ro', name: 'Romanian; Moldavian; Moldovan' },
  { code: 'ru', name: 'Russian' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'sa', name: 'Sanskrit' },
  { code: 'sc', name: 'Sardinian' },
  { code: 'sd', name: 'Sindhi' },
  { code: 'se', name: 'Northern Sami' },
  { code: 'sg', name: 'Sango' },
  { code: 'si', name: 'Sinhala; Sinhalese' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'sm', name: 'Samoan' },
  { code: 'sn', name: 'Shona' },
  { code: 'so', name: 'Somali' },
  { code: 'sq', name: 'Albanian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'ss', name: 'Swati' },
  { code: 'st', name: 'Sotho, Southern' },
  { code: 'su', name: 'Sundanese' },
  { code: 'sv', name: 'Swedish' },
  { code: 'sw', name: 'Swahili' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'tg', name: 'Tajik' },
  { code: 'th', name: 'Thai' },
  { code: 'ti', name: 'Tigrinya' },
  { code: 'tk', name: 'Turkmen' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'tn', name: 'Tswana' },
  { code: 'to', name: 'Tonga (Tonga Islands)' },
  { code: 'tr', name: 'Turkish' },
  { code: 'ts', name: 'Tsonga' },
  { code: 'tt', name: 'Tatar' },
  { code: 'tw', name: 'Twi' },
  { code: 'ty', name: 'Tahitian' },
  { code: 'ug', name: 'Uighur; Uyghur' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'uz', name: 'Uzbek' },
  { code: 've', name: 'Venda' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'vo', name: 'Volapük' },
  { code: 'wa', name: 'Walloon' },
  { code: 'wo', name: 'Wolof' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'yi', name: 'Yiddish' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'za', name: 'Zhuang; Chuang' },
  { code: 'zh', name: 'Chinese' },
  { code: 'zu', name: 'Zulu' },
];
