import type { Country } from '@/component/types'

export const countryInformation: Country[] = [
  { name: 'South Georgia', iso2: 'GS', dialCode: '+500', dialCodeSuffixes: [], flag: '🇬🇸', invalid: false },
  { name: 'Grenada', iso2: 'GD', dialCode: '+1473', dialCodeSuffixes: [], flag: '🇬🇩', invalid: false },
  { name: 'Switzerland', iso2: 'CH', dialCode: '+41', dialCodeSuffixes: [], flag: '🇨🇭', invalid: false },
  { name: 'Sierra Leone', iso2: 'SL', dialCode: '+232', dialCodeSuffixes: [], flag: '🇸🇱', invalid: false },
  { name: 'Hungary', iso2: 'HU', dialCode: '+36', dialCodeSuffixes: [], flag: '🇭🇺', invalid: false },
  { name: 'Taiwan', iso2: 'TW', dialCode: '+886', dialCodeSuffixes: [], flag: '🇹🇼', invalid: false },
  { name: 'Wallis and Futuna', iso2: 'WF', dialCode: '+681', dialCodeSuffixes: [], flag: '🇼🇫', invalid: false },
  { name: 'Barbados', iso2: 'BB', dialCode: '+1246', dialCodeSuffixes: [], flag: '🇧🇧', invalid: false },
  { name: 'Pitcairn Islands', iso2: 'PN', dialCode: '+64', dialCodeSuffixes: [], flag: '🇵🇳', invalid: false },
  { name: 'Ivory Coast', iso2: 'CI', dialCode: '+225', dialCodeSuffixes: [], flag: '🇨🇮', invalid: false },
  { name: 'Tunisia', iso2: 'TN', dialCode: '+216', dialCodeSuffixes: [], flag: '🇹🇳', invalid: false },
  { name: 'Italy', iso2: 'IT', dialCode: '+39', dialCodeSuffixes: [], flag: '🇮🇹', invalid: false },
  { name: 'Benin', iso2: 'BJ', dialCode: '+229', dialCodeSuffixes: [], flag: '🇧🇯', invalid: false },
  { name: 'Indonesia', iso2: 'ID', dialCode: '+62', dialCodeSuffixes: [], flag: '🇮🇩', invalid: false },
  { name: 'Cape Verde', iso2: 'CV', dialCode: '+238', dialCodeSuffixes: [], flag: '🇨🇻', invalid: false },
  { name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '+1869', dialCodeSuffixes: [], flag: '🇰🇳', invalid: false },
  { name: 'Laos', iso2: 'LA', dialCode: '+856', dialCodeSuffixes: [], flag: '🇱🇦', invalid: false },
  { name: 'Caribbean Netherlands', iso2: 'BQ', dialCode: '+599', dialCodeSuffixes: [], flag: '🇧🇶', invalid: false },
  { name: 'Uganda', iso2: 'UG', dialCode: '+256', dialCodeSuffixes: [], flag: '🇺🇬', invalid: false },
  { name: 'Andorra', iso2: 'AD', dialCode: '+376', dialCodeSuffixes: [], flag: '🇦🇩', invalid: false },
  { name: 'Burundi', iso2: 'BI', dialCode: '+257', dialCodeSuffixes: [], flag: '🇧🇮', invalid: false },
  { name: 'South Africa', iso2: 'ZA', dialCode: '+27', dialCodeSuffixes: [], flag: '🇿🇦', invalid: false },
  { name: 'France', iso2: 'FR', dialCode: '+33', dialCodeSuffixes: [], flag: '🇫🇷', invalid: false },
  { name: 'Libya', iso2: 'LY', dialCode: '+218', dialCodeSuffixes: [], flag: '🇱🇾', invalid: false },
  { name: 'Mexico', iso2: 'MX', dialCode: '+52', dialCodeSuffixes: [], flag: '🇲🇽', invalid: false },
  { name: 'Gabon', iso2: 'GA', dialCode: '+241', dialCodeSuffixes: [], flag: '🇬🇦', invalid: false },
  { name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '+1670', dialCodeSuffixes: [], flag: '🇲🇵', invalid: false },
  { name: 'North Macedonia', iso2: 'MK', dialCode: '+389', dialCodeSuffixes: [], flag: '🇲🇰', invalid: false },
  { name: 'China', iso2: 'CN', dialCode: '+86', dialCodeSuffixes: [], flag: '🇨🇳', invalid: false },
  { name: 'Yemen', iso2: 'YE', dialCode: '+967', dialCodeSuffixes: [], flag: '🇾🇪', invalid: false },
  { name: 'Saint Barthélemy', iso2: 'BL', dialCode: '+590', dialCodeSuffixes: [], flag: '🇧🇱', invalid: false },
  { name: 'Guernsey', iso2: 'GG', dialCode: '+44', dialCodeSuffixes: [], flag: '🇬🇬', invalid: false },
  { name: 'Solomon Islands', iso2: 'SB', dialCode: '+677', dialCodeSuffixes: [], flag: '🇸🇧', invalid: false },
  { name: 'Svalbard and Jan Mayen', iso2: 'SJ', dialCode: '+4779', dialCodeSuffixes: [], flag: '🇸🇯', invalid: false },
  { name: 'Faroe Islands', iso2: 'FO', dialCode: '+298', dialCodeSuffixes: [], flag: '🇫🇴', invalid: false },
  { name: 'Uzbekistan', iso2: 'UZ', dialCode: '+998', dialCodeSuffixes: [], flag: '🇺🇿', invalid: false },
  { name: 'Egypt', iso2: 'EG', dialCode: '+20', dialCodeSuffixes: [], flag: '🇪🇬', invalid: false },
  { name: 'Senegal', iso2: 'SN', dialCode: '+221', dialCodeSuffixes: [], flag: '🇸🇳', invalid: false },
  { name: 'Sri Lanka', iso2: 'LK', dialCode: '+94', dialCodeSuffixes: [], flag: '🇱🇰', invalid: false },
  { name: 'Palestine', iso2: 'PS', dialCode: '+970', dialCodeSuffixes: [], flag: '🇵🇸', invalid: false },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '+880', dialCodeSuffixes: [], flag: '🇧🇩', invalid: false },
  { name: 'Peru', iso2: 'PE', dialCode: '+51', dialCodeSuffixes: [], flag: '🇵🇪', invalid: false },
  { name: 'Singapore', iso2: 'SG', dialCode: '+65', dialCodeSuffixes: [], flag: '🇸🇬', invalid: false },
  { name: 'Turkey', iso2: 'TR', dialCode: '+90', dialCodeSuffixes: [], flag: '🇹🇷', invalid: false },
  { name: 'Afghanistan', iso2: 'AF', dialCode: '+93', dialCodeSuffixes: [], flag: '🇦🇫', invalid: false },
  { name: 'Aruba', iso2: 'AW', dialCode: '+297', dialCodeSuffixes: [], flag: '🇦🇼', invalid: false },
  { name: 'Cook Islands', iso2: 'CK', dialCode: '+682', dialCodeSuffixes: [], flag: '🇨🇰', invalid: false },
  { name: 'United Kingdom', iso2: 'GB', dialCode: '+44', dialCodeSuffixes: [], flag: '🇬🇧', invalid: false },
  { name: 'Zambia', iso2: 'ZM', dialCode: '+260', dialCodeSuffixes: [], flag: '🇿🇲', invalid: false },
  { name: 'Finland', iso2: 'FI', dialCode: '+358', dialCodeSuffixes: [], flag: '🇫🇮', invalid: false },
  { name: 'Niger', iso2: 'NE', dialCode: '+227', dialCodeSuffixes: [], flag: '🇳🇪', invalid: false },
  { name: 'Christmas Island', iso2: 'CX', dialCode: '+61', dialCodeSuffixes: [], flag: '🇨🇽', invalid: false },
  { name: 'Tokelau', iso2: 'TK', dialCode: '+690', dialCodeSuffixes: [], flag: '🇹🇰', invalid: false },
  { name: 'Guinea-Bissau', iso2: 'GW', dialCode: '+245', dialCodeSuffixes: [], flag: '🇬🇼', invalid: false },
  { name: 'Azerbaijan', iso2: 'AZ', dialCode: '+994', dialCodeSuffixes: [], flag: '🇦🇿', invalid: false },
  { name: 'Réunion', iso2: 'RE', dialCode: '+262', dialCodeSuffixes: [], flag: '🇷🇪', invalid: false },
  { name: 'Djibouti', iso2: 'DJ', dialCode: '+253', dialCodeSuffixes: [], flag: '🇩🇯', invalid: false },
  { name: 'North Korea', iso2: 'KP', dialCode: '+850', dialCodeSuffixes: [], flag: '🇰🇵', invalid: false },
  { name: 'Mauritius', iso2: 'MU', dialCode: '+230', dialCodeSuffixes: [], flag: '🇲🇺', invalid: false },
  { name: 'Montserrat', iso2: 'MS', dialCode: '+1664', dialCodeSuffixes: [], flag: '🇲🇸', invalid: false },
  {
    name: 'United States Virgin Islands',
    iso2: 'VI',
    dialCode: '+1340',
    dialCodeSuffixes: [],
    flag: '🇻🇮',
    invalid: false,
  },
  { name: 'Colombia', iso2: 'CO', dialCode: '+57', dialCodeSuffixes: [], flag: '🇨🇴', invalid: false },
  { name: 'Greece', iso2: 'GR', dialCode: '+30', dialCodeSuffixes: [], flag: '🇬🇷', invalid: false },
  { name: 'Croatia', iso2: 'HR', dialCode: '+385', dialCodeSuffixes: [], flag: '🇭🇷', invalid: false },
  { name: 'Morocco', iso2: 'MA', dialCode: '+212', dialCodeSuffixes: [], flag: '🇲🇦', invalid: false },
  { name: 'Algeria', iso2: 'DZ', dialCode: '+213', dialCodeSuffixes: [], flag: '🇩🇿', invalid: false },
  { name: 'Netherlands', iso2: 'NL', dialCode: '+31', dialCodeSuffixes: [], flag: '🇳🇱', invalid: false },
  { name: 'Sudan', iso2: 'SD', dialCode: '+249', dialCodeSuffixes: [], flag: '🇸🇩', invalid: false },
  { name: 'Fiji', iso2: 'FJ', dialCode: '+679', dialCodeSuffixes: [], flag: '🇫🇯', invalid: false },
  { name: 'Liechtenstein', iso2: 'LI', dialCode: '+423', dialCodeSuffixes: [], flag: '🇱🇮', invalid: false },
  { name: 'Nepal', iso2: 'NP', dialCode: '+977', dialCodeSuffixes: [], flag: '🇳🇵', invalid: false },
  { name: 'Puerto Rico', iso2: 'PR', dialCode: '+1', dialCodeSuffixes: ['787', '939'], flag: '🇵🇷', invalid: false },
  { name: 'Georgia', iso2: 'GE', dialCode: '+995', dialCodeSuffixes: [], flag: '🇬🇪', invalid: false },
  { name: 'Pakistan', iso2: 'PK', dialCode: '+92', dialCodeSuffixes: [], flag: '🇵🇰', invalid: false },
  { name: 'Monaco', iso2: 'MC', dialCode: '+377', dialCodeSuffixes: [], flag: '🇲🇨', invalid: false },
  { name: 'Botswana', iso2: 'BW', dialCode: '+267', dialCodeSuffixes: [], flag: '🇧🇼', invalid: false },
  { name: 'Lebanon', iso2: 'LB', dialCode: '+961', dialCodeSuffixes: [], flag: '🇱🇧', invalid: false },
  { name: 'Papua New Guinea', iso2: 'PG', dialCode: '+675', dialCodeSuffixes: [], flag: '🇵🇬', invalid: false },
  { name: 'Mayotte', iso2: 'YT', dialCode: '+262', dialCodeSuffixes: [], flag: '🇾🇹', invalid: false },
  {
    name: 'Dominican Republic',
    iso2: 'DO',
    dialCode: '+1',
    dialCodeSuffixes: ['809', '829', '849'],
    flag: '🇩🇴',
    invalid: false,
  },
  { name: 'Norfolk Island', iso2: 'NF', dialCode: '+672', dialCodeSuffixes: [], flag: '🇳🇫', invalid: false },
  { name: 'Bouvet Island', iso2: 'BV', dialCode: '+47', dialCodeSuffixes: [], flag: '🇧🇻', invalid: false },
  { name: 'Qatar', iso2: 'QA', dialCode: '+974', dialCodeSuffixes: [], flag: '🇶🇦', invalid: false },
  { name: 'Madagascar', iso2: 'MG', dialCode: '+261', dialCodeSuffixes: [], flag: '🇲🇬', invalid: false },
  { name: 'India', iso2: 'IN', dialCode: '+91', dialCodeSuffixes: [], flag: '🇮🇳', invalid: false },
  { name: 'Syria', iso2: 'SY', dialCode: '+963', dialCodeSuffixes: [], flag: '🇸🇾', invalid: false },
  { name: 'Montenegro', iso2: 'ME', dialCode: '+382', dialCodeSuffixes: [], flag: '🇲🇪', invalid: false },
  { name: 'Eswatini', iso2: 'SZ', dialCode: '+268', dialCodeSuffixes: [], flag: '🇸🇿', invalid: false },
  { name: 'Paraguay', iso2: 'PY', dialCode: '+595', dialCodeSuffixes: [], flag: '🇵🇾', invalid: false },
  { name: 'El Salvador', iso2: 'SV', dialCode: '+503', dialCodeSuffixes: [], flag: '🇸🇻', invalid: false },
  { name: 'Ukraine', iso2: 'UA', dialCode: '+380', dialCodeSuffixes: [], flag: '🇺🇦', invalid: false },
  { name: 'Isle of Man', iso2: 'IM', dialCode: '+44', dialCodeSuffixes: [], flag: '🇮🇲', invalid: false },
  { name: 'Namibia', iso2: 'NA', dialCode: '+264', dialCodeSuffixes: [], flag: '🇳🇦', invalid: false },
  { name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971', dialCodeSuffixes: [], flag: '🇦🇪', invalid: false },
  { name: 'Bulgaria', iso2: 'BG', dialCode: '+359', dialCodeSuffixes: [], flag: '🇧🇬', invalid: false },
  { name: 'Greenland', iso2: 'GL', dialCode: '+299', dialCodeSuffixes: [], flag: '🇬🇱', invalid: false },
  { name: 'Germany', iso2: 'DE', dialCode: '+49', dialCodeSuffixes: [], flag: '🇩🇪', invalid: false },
  { name: 'Cambodia', iso2: 'KH', dialCode: '+855', dialCodeSuffixes: [], flag: '🇰🇭', invalid: false },
  { name: 'Iraq', iso2: 'IQ', dialCode: '+964', dialCodeSuffixes: [], flag: '🇮🇶', invalid: false },
  {
    name: 'French Southern and Antarctic Lands',
    iso2: 'TF',
    dialCode: '+262',
    dialCodeSuffixes: [],
    flag: '🇹🇫',
    invalid: false,
  },
  { name: 'Sweden', iso2: 'SE', dialCode: '+46', dialCodeSuffixes: [], flag: '🇸🇪', invalid: false },
  { name: 'Cuba', iso2: 'CU', dialCode: '+53', dialCodeSuffixes: [], flag: '🇨🇺', invalid: false },
  { name: 'Kyrgyzstan', iso2: 'KG', dialCode: '+996', dialCodeSuffixes: [], flag: '🇰🇬', invalid: false },
  {
    name: 'Russia',
    iso2: 'RU',
    dialCode: '+7',
    dialCodeSuffixes: ['3', '4', '5', '8', '9'],
    flag: '🇷🇺',
    invalid: false,
  },
  { name: 'Malaysia', iso2: 'MY', dialCode: '+60', dialCodeSuffixes: [], flag: '🇲🇾', invalid: false },
  { name: 'São Tomé and Príncipe', iso2: 'ST', dialCode: '+239', dialCodeSuffixes: [], flag: '🇸🇹', invalid: false },
  { name: 'Cyprus', iso2: 'CY', dialCode: '+357', dialCodeSuffixes: [], flag: '🇨🇾', invalid: false },
  { name: 'Canada', iso2: 'CA', dialCode: '+1', dialCodeSuffixes: [], flag: '🇨🇦', invalid: false },
  { name: 'Malawi', iso2: 'MW', dialCode: '+265', dialCodeSuffixes: [], flag: '🇲🇼', invalid: false },
  { name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966', dialCodeSuffixes: [], flag: '🇸🇦', invalid: false },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '+387', dialCodeSuffixes: [], flag: '🇧🇦', invalid: false },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '+251', dialCodeSuffixes: [], flag: '🇪🇹', invalid: false },
  { name: 'Spain', iso2: 'ES', dialCode: '+34', dialCodeSuffixes: [], flag: '🇪🇸', invalid: false },
  { name: 'Slovenia', iso2: 'SI', dialCode: '+386', dialCodeSuffixes: [], flag: '🇸🇮', invalid: false },
  { name: 'Oman', iso2: 'OM', dialCode: '+968', dialCodeSuffixes: [], flag: '🇴🇲', invalid: false },
  { name: 'Saint Pierre and Miquelon', iso2: 'PM', dialCode: '+508', dialCodeSuffixes: [], flag: '🇵🇲', invalid: false },
  { name: 'Macau', iso2: 'MO', dialCode: '+853', dialCodeSuffixes: [], flag: '🇲🇴', invalid: false },
  { name: 'San Marino', iso2: 'SM', dialCode: '+378', dialCodeSuffixes: [], flag: '🇸🇲', invalid: false },
  { name: 'Lesotho', iso2: 'LS', dialCode: '+266', dialCodeSuffixes: [], flag: '🇱🇸', invalid: false },
  { name: 'Marshall Islands', iso2: 'MH', dialCode: '+692', dialCodeSuffixes: [], flag: '🇲🇭', invalid: false },
  { name: 'Sint Maarten', iso2: 'SX', dialCode: '+1721', dialCodeSuffixes: [], flag: '🇸🇽', invalid: false },
  { name: 'Iceland', iso2: 'IS', dialCode: '+354', dialCodeSuffixes: [], flag: '🇮🇸', invalid: false },
  { name: 'Luxembourg', iso2: 'LU', dialCode: '+352', dialCodeSuffixes: [], flag: '🇱🇺', invalid: false },
  { name: 'Argentina', iso2: 'AR', dialCode: '+54', dialCodeSuffixes: [], flag: '🇦🇷', invalid: false },
  { name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '+1649', dialCodeSuffixes: [], flag: '🇹🇨', invalid: false },
  { name: 'Nauru', iso2: 'NR', dialCode: '+674', dialCodeSuffixes: [], flag: '🇳🇷', invalid: false },
  { name: 'Cocos (Keeling) Islands', iso2: 'CC', dialCode: '+61', dialCodeSuffixes: [], flag: '🇨🇨', invalid: false },
  {
    name: 'Western Sahara',
    iso2: 'EH',
    dialCode: '+2',
    dialCodeSuffixes: ['125288', '125289'],
    flag: '🇪🇭',
    invalid: false,
  },
  { name: 'Dominica', iso2: 'DM', dialCode: '+1767', dialCodeSuffixes: [], flag: '🇩🇲', invalid: false },
  { name: 'Costa Rica', iso2: 'CR', dialCode: '+506', dialCodeSuffixes: [], flag: '🇨🇷', invalid: false },
  { name: 'Australia', iso2: 'AU', dialCode: '+61', dialCodeSuffixes: [], flag: '🇦🇺', invalid: false },
  { name: 'Thailand', iso2: 'TH', dialCode: '+66', dialCodeSuffixes: [], flag: '🇹🇭', invalid: false },
  { name: 'Haiti', iso2: 'HT', dialCode: '+509', dialCodeSuffixes: [], flag: '🇭🇹', invalid: false },
  { name: 'Tuvalu', iso2: 'TV', dialCode: '+688', dialCodeSuffixes: [], flag: '🇹🇻', invalid: false },
  { name: 'Honduras', iso2: 'HN', dialCode: '+504', dialCodeSuffixes: [], flag: '🇭🇳', invalid: false },
  { name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '+240', dialCodeSuffixes: [], flag: '🇬🇶', invalid: false },
  { name: 'Saint Lucia', iso2: 'LC', dialCode: '+1758', dialCodeSuffixes: [], flag: '🇱🇨', invalid: false },
  { name: 'French Polynesia', iso2: 'PF', dialCode: '+689', dialCodeSuffixes: [], flag: '🇵🇫', invalid: false },
  { name: 'Belarus', iso2: 'BY', dialCode: '+375', dialCodeSuffixes: [], flag: '🇧🇾', invalid: false },
  { name: 'Latvia', iso2: 'LV', dialCode: '+371', dialCodeSuffixes: [], flag: '🇱🇻', invalid: false },
  { name: 'Palau', iso2: 'PW', dialCode: '+680', dialCodeSuffixes: [], flag: '🇵🇼', invalid: false },
  { name: 'Guadeloupe', iso2: 'GP', dialCode: '+590', dialCodeSuffixes: [], flag: '🇬🇵', invalid: false },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63', dialCodeSuffixes: [], flag: '🇵🇭', invalid: false },
  { name: 'Gibraltar', iso2: 'GI', dialCode: '+350', dialCodeSuffixes: [], flag: '🇬🇮', invalid: false },
  { name: 'Denmark', iso2: 'DK', dialCode: '+45', dialCodeSuffixes: [], flag: '🇩🇰', invalid: false },
  { name: 'Cameroon', iso2: 'CM', dialCode: '+237', dialCodeSuffixes: [], flag: '🇨🇲', invalid: false },
  { name: 'Guinea', iso2: 'GN', dialCode: '+224', dialCodeSuffixes: [], flag: '🇬🇳', invalid: false },
  { name: 'Bahrain', iso2: 'BH', dialCode: '+973', dialCodeSuffixes: [], flag: '🇧🇭', invalid: false },
  { name: 'Suriname', iso2: 'SR', dialCode: '+597', dialCodeSuffixes: [], flag: '🇸🇷', invalid: false },
  { name: 'DR Congo', iso2: 'CD', dialCode: '+243', dialCodeSuffixes: [], flag: '🇨🇩', invalid: false },
  { name: 'Somalia', iso2: 'SO', dialCode: '+252', dialCodeSuffixes: [], flag: '🇸🇴', invalid: false },
  { name: 'Czechia', iso2: 'CZ', dialCode: '+420', dialCodeSuffixes: [], flag: '🇨🇿', invalid: false },
  { name: 'New Caledonia', iso2: 'NC', dialCode: '+687', dialCodeSuffixes: [], flag: '🇳🇨', invalid: false },
  { name: 'Vanuatu', iso2: 'VU', dialCode: '+678', dialCodeSuffixes: [], flag: '🇻🇺', invalid: false },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    iso2: 'SH',
    dialCode: '+2',
    dialCodeSuffixes: ['90', '47'],
    flag: '🇸🇭',
    invalid: false,
  },
  { name: 'Togo', iso2: 'TG', dialCode: '+228', dialCodeSuffixes: [], flag: '🇹🇬', invalid: false },
  { name: 'British Virgin Islands', iso2: 'VG', dialCode: '+1284', dialCodeSuffixes: [], flag: '🇻🇬', invalid: false },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254', dialCodeSuffixes: [], flag: '🇰🇪', invalid: false },
  { name: 'Niue', iso2: 'NU', dialCode: '+683', dialCodeSuffixes: [], flag: '🇳🇺', invalid: false },
  { name: 'Rwanda', iso2: 'RW', dialCode: '+250', dialCodeSuffixes: [], flag: '🇷🇼', invalid: false },
  { name: 'Estonia', iso2: 'EE', dialCode: '+372', dialCodeSuffixes: [], flag: '🇪🇪', invalid: false },
  { name: 'Romania', iso2: 'RO', dialCode: '+40', dialCodeSuffixes: [], flag: '🇷🇴', invalid: false },
  { name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '+1868', dialCodeSuffixes: [], flag: '🇹🇹', invalid: false },
  { name: 'Guyana', iso2: 'GY', dialCode: '+592', dialCodeSuffixes: [], flag: '🇬🇾', invalid: false },
  { name: 'Timor-Leste', iso2: 'TL', dialCode: '+670', dialCodeSuffixes: [], flag: '🇹🇱', invalid: false },
  { name: 'Vietnam', iso2: 'VN', dialCode: '+84', dialCodeSuffixes: [], flag: '🇻🇳', invalid: false },
  { name: 'Uruguay', iso2: 'UY', dialCode: '+598', dialCodeSuffixes: [], flag: '🇺🇾', invalid: false },
  { name: 'Vatican City', iso2: 'VA', dialCode: '+3', dialCodeSuffixes: ['906698', '79'], flag: '🇻🇦', invalid: false },
  { name: 'Hong Kong', iso2: 'HK', dialCode: '+852', dialCodeSuffixes: [], flag: '🇭🇰', invalid: false },
  { name: 'Austria', iso2: 'AT', dialCode: '+43', dialCodeSuffixes: [], flag: '🇦🇹', invalid: false },
  { name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '+1268', dialCodeSuffixes: [], flag: '🇦🇬', invalid: false },
  { name: 'Turkmenistan', iso2: 'TM', dialCode: '+993', dialCodeSuffixes: [], flag: '🇹🇲', invalid: false },
  { name: 'Mozambique', iso2: 'MZ', dialCode: '+258', dialCodeSuffixes: [], flag: '🇲🇿', invalid: false },
  { name: 'Panama', iso2: 'PA', dialCode: '+507', dialCodeSuffixes: [], flag: '🇵🇦', invalid: false },
  { name: 'Micronesia', iso2: 'FM', dialCode: '+691', dialCodeSuffixes: [], flag: '🇫🇲', invalid: false },
  { name: 'Ireland', iso2: 'IE', dialCode: '+353', dialCodeSuffixes: [], flag: '🇮🇪', invalid: false },
  { name: 'Curaçao', iso2: 'CW', dialCode: '+599', dialCodeSuffixes: [], flag: '🇨🇼', invalid: false },
  { name: 'French Guiana', iso2: 'GF', dialCode: '+594', dialCodeSuffixes: [], flag: '🇬🇫', invalid: false },
  { name: 'Norway', iso2: 'NO', dialCode: '+47', dialCodeSuffixes: [], flag: '🇳🇴', invalid: false },
  { name: 'Åland Islands', iso2: 'AX', dialCode: '+35818', dialCodeSuffixes: [], flag: '🇦🇽', invalid: false },
  { name: 'Central African Republic', iso2: 'CF', dialCode: '+236', dialCodeSuffixes: [], flag: '🇨🇫', invalid: false },
  { name: 'Burkina Faso', iso2: 'BF', dialCode: '+226', dialCodeSuffixes: [], flag: '🇧🇫', invalid: false },
  { name: 'Eritrea', iso2: 'ER', dialCode: '+291', dialCodeSuffixes: [], flag: '🇪🇷', invalid: false },
  { name: 'Tanzania', iso2: 'TZ', dialCode: '+255', dialCodeSuffixes: [], flag: '🇹🇿', invalid: false },
  { name: 'South Korea', iso2: 'KR', dialCode: '+82', dialCodeSuffixes: [], flag: '🇰🇷', invalid: false },
  { name: 'Jordan', iso2: 'JO', dialCode: '+962', dialCodeSuffixes: [], flag: '🇯🇴', invalid: false },
  { name: 'Mauritania', iso2: 'MR', dialCode: '+222', dialCodeSuffixes: [], flag: '🇲🇷', invalid: false },
  { name: 'Lithuania', iso2: 'LT', dialCode: '+370', dialCodeSuffixes: [], flag: '🇱🇹', invalid: false },
  {
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    dialCode: '+268',
    dialCodeSuffixes: [],
    flag: '🇺🇲',
    invalid: false,
  },
  { name: 'Slovakia', iso2: 'SK', dialCode: '+421', dialCodeSuffixes: [], flag: '🇸🇰', invalid: false },
  { name: 'Angola', iso2: 'AO', dialCode: '+244', dialCodeSuffixes: [], flag: '🇦🇴', invalid: false },
  { name: 'Kazakhstan', iso2: 'KZ', dialCode: '+7', dialCodeSuffixes: ['6', '7'], flag: '🇰🇿', invalid: false },
  { name: 'Moldova', iso2: 'MD', dialCode: '+373', dialCodeSuffixes: [], flag: '🇲🇩', invalid: false },
  { name: 'Mali', iso2: 'ML', dialCode: '+223', dialCodeSuffixes: [], flag: '🇲🇱', invalid: false },
  { name: 'Falkland Islands', iso2: 'FK', dialCode: '+500', dialCodeSuffixes: [], flag: '🇫🇰', invalid: false },
  { name: 'Armenia', iso2: 'AM', dialCode: '+374', dialCodeSuffixes: [], flag: '🇦🇲', invalid: false },
  { name: 'Samoa', iso2: 'WS', dialCode: '+685', dialCodeSuffixes: [], flag: '🇼🇸', invalid: false },
  { name: 'Jersey', iso2: 'JE', dialCode: '+44', dialCodeSuffixes: [], flag: '🇯🇪', invalid: false },
  { name: 'Japan', iso2: 'JP', dialCode: '+81', dialCodeSuffixes: [], flag: '🇯🇵', invalid: false },
  { name: 'Bolivia', iso2: 'BO', dialCode: '+591', dialCodeSuffixes: [], flag: '🇧🇴', invalid: false },
  { name: 'Chile', iso2: 'CL', dialCode: '+56', dialCodeSuffixes: [], flag: '🇨🇱', invalid: false },
  {
    name: 'United States',
    iso2: 'US',
    dialCode: '+1',
    dialCodeSuffixes: [
      '201',
      '202',
      '203',
      '205',
      '206',
      '207',
      '208',
      '209',
      '210',
      '212',
      '213',
      '214',
      '215',
      '216',
      '217',
      '218',
      '219',
      '220',
      '224',
      '225',
      '227',
      '228',
      '229',
      '231',
      '234',
      '239',
      '240',
      '248',
      '251',
      '252',
      '253',
      '254',
      '256',
      '260',
      '262',
      '267',
      '269',
      '270',
      '272',
      '274',
      '276',
      '281',
      '283',
      '301',
      '302',
      '303',
      '304',
      '305',
      '307',
      '308',
      '309',
      '310',
      '312',
      '313',
      '314',
      '315',
      '316',
      '317',
      '318',
      '319',
      '320',
      '321',
      '323',
      '325',
      '327',
      '330',
      '331',
      '334',
      '336',
      '337',
      '339',
      '346',
      '347',
      '351',
      '352',
      '360',
      '361',
      '364',
      '380',
      '385',
      '386',
      '401',
      '402',
      '404',
      '405',
      '406',
      '407',
      '408',
      '409',
      '410',
      '412',
      '413',
      '414',
      '415',
      '417',
      '419',
      '423',
      '424',
      '425',
      '430',
      '432',
      '434',
      '435',
      '440',
      '442',
      '443',
      '447',
      '458',
      '463',
      '464',
      '469',
      '470',
      '475',
      '478',
      '479',
      '480',
      '484',
      '501',
      '502',
      '503',
      '504',
      '505',
      '507',
      '508',
      '509',
      '510',
      '512',
      '513',
      '515',
      '516',
      '517',
      '518',
      '520',
      '530',
      '531',
      '534',
      '539',
      '540',
      '541',
      '551',
      '559',
      '561',
      '562',
      '563',
      '564',
      '567',
      '570',
      '571',
      '573',
      '574',
      '575',
      '580',
      '585',
      '586',
      '601',
      '602',
      '603',
      '605',
      '606',
      '607',
      '608',
      '609',
      '610',
      '612',
      '614',
      '615',
      '616',
      '617',
      '618',
      '619',
      '620',
      '623',
      '626',
      '628',
      '629',
      '630',
      '631',
      '636',
      '641',
      '646',
      '650',
      '651',
      '657',
      '660',
      '661',
      '662',
      '667',
      '669',
      '678',
      '681',
      '682',
      '701',
      '702',
      '703',
      '704',
      '706',
      '707',
      '708',
      '712',
      '713',
      '714',
      '715',
      '716',
      '717',
      '718',
      '719',
      '720',
      '724',
      '725',
      '727',
      '730',
      '731',
      '732',
      '734',
      '737',
      '740',
      '743',
      '747',
      '754',
      '757',
      '760',
      '762',
      '763',
      '765',
      '769',
      '770',
      '772',
      '773',
      '774',
      '775',
      '779',
      '781',
      '785',
      '786',
      '801',
      '802',
      '803',
      '804',
      '805',
      '806',
      '808',
      '810',
      '812',
      '813',
      '814',
      '815',
      '816',
      '817',
      '818',
      '828',
      '830',
      '831',
      '832',
      '843',
      '845',
      '847',
      '848',
      '850',
      '854',
      '856',
      '857',
      '858',
      '859',
      '860',
      '862',
      '863',
      '864',
      '865',
      '870',
      '872',
      '878',
      '901',
      '903',
      '904',
      '906',
      '907',
      '908',
      '909',
      '910',
      '912',
      '913',
      '914',
      '915',
      '916',
      '917',
      '918',
      '919',
      '920',
      '925',
      '928',
      '929',
      '930',
      '931',
      '934',
      '936',
      '937',
      '938',
      '940',
      '941',
      '947',
      '949',
      '951',
      '952',
      '954',
      '956',
      '959',
      '970',
      '971',
      '972',
      '973',
      '975',
      '978',
      '979',
      '980',
      '984',
      '985',
      '989',
    ],
    flag: '🇺🇸',
    invalid: false,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    dialCode: '+1784',
    dialCodeSuffixes: [],
    flag: '🇻🇨',
    invalid: false,
  },
  { name: 'Bermuda', iso2: 'BM', dialCode: '+1441', dialCodeSuffixes: [], flag: '🇧🇲', invalid: false },
  { name: 'Seychelles', iso2: 'SC', dialCode: '+248', dialCodeSuffixes: [], flag: '🇸🇨', invalid: false },
  {
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    dialCode: '+246',
    dialCodeSuffixes: [],
    flag: '🇮🇴',
    invalid: false,
  },
  { name: 'Guatemala', iso2: 'GT', dialCode: '+502', dialCodeSuffixes: [], flag: '🇬🇹', invalid: false },
  { name: 'Ecuador', iso2: 'EC', dialCode: '+593', dialCodeSuffixes: [], flag: '🇪🇨', invalid: false },
  { name: 'Martinique', iso2: 'MQ', dialCode: '+596', dialCodeSuffixes: [], flag: '🇲🇶', invalid: false },
  { name: 'Tajikistan', iso2: 'TJ', dialCode: '+992', dialCodeSuffixes: [], flag: '🇹🇯', invalid: false },
  { name: 'Malta', iso2: 'MT', dialCode: '+356', dialCodeSuffixes: [], flag: '🇲🇹', invalid: false },
  { name: 'Gambia', iso2: 'GM', dialCode: '+220', dialCodeSuffixes: [], flag: '🇬🇲', invalid: false },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234', dialCodeSuffixes: [], flag: '🇳🇬', invalid: false },
  { name: 'Bahamas', iso2: 'BS', dialCode: '+1242', dialCodeSuffixes: [], flag: '🇧🇸', invalid: false },
  { name: 'Kosovo', iso2: 'XK', dialCode: '+383', dialCodeSuffixes: [], flag: '🇽🇰', invalid: false },
  { name: 'Kuwait', iso2: 'KW', dialCode: '+965', dialCodeSuffixes: [], flag: '🇰🇼', invalid: false },
  { name: 'Maldives', iso2: 'MV', dialCode: '+960', dialCodeSuffixes: [], flag: '🇲🇻', invalid: false },
  { name: 'South Sudan', iso2: 'SS', dialCode: '+211', dialCodeSuffixes: [], flag: '🇸🇸', invalid: false },
  { name: 'Iran', iso2: 'IR', dialCode: '+98', dialCodeSuffixes: [], flag: '🇮🇷', invalid: false },
  { name: 'Albania', iso2: 'AL', dialCode: '+355', dialCodeSuffixes: [], flag: '🇦🇱', invalid: false },
  { name: 'Brazil', iso2: 'BR', dialCode: '+55', dialCodeSuffixes: [], flag: '🇧🇷', invalid: false },
  { name: 'Serbia', iso2: 'RS', dialCode: '+381', dialCodeSuffixes: [], flag: '🇷🇸', invalid: false },
  { name: 'Belize', iso2: 'BZ', dialCode: '+501', dialCodeSuffixes: [], flag: '🇧🇿', invalid: false },
  { name: 'Myanmar', iso2: 'MM', dialCode: '+95', dialCodeSuffixes: [], flag: '🇲🇲', invalid: false },
  { name: 'Bhutan', iso2: 'BT', dialCode: '+975', dialCodeSuffixes: [], flag: '🇧🇹', invalid: false },
  { name: 'Venezuela', iso2: 'VE', dialCode: '+58', dialCodeSuffixes: [], flag: '🇻🇪', invalid: false },
  { name: 'Liberia', iso2: 'LR', dialCode: '+231', dialCodeSuffixes: [], flag: '🇱🇷', invalid: false },
  { name: 'Jamaica', iso2: 'JM', dialCode: '+1876', dialCodeSuffixes: [], flag: '🇯🇲', invalid: false },
  { name: 'Poland', iso2: 'PL', dialCode: '+48', dialCodeSuffixes: [], flag: '🇵🇱', invalid: false },
  { name: 'Cayman Islands', iso2: 'KY', dialCode: '+1345', dialCodeSuffixes: [], flag: '🇰🇾', invalid: false },
  { name: 'Brunei', iso2: 'BN', dialCode: '+673', dialCodeSuffixes: [], flag: '🇧🇳', invalid: false },
  { name: 'Comoros', iso2: 'KM', dialCode: '+269', dialCodeSuffixes: [], flag: '🇰🇲', invalid: false },
  { name: 'Guam', iso2: 'GU', dialCode: '+1671', dialCodeSuffixes: [], flag: '🇬🇺', invalid: false },
  { name: 'Tonga', iso2: 'TO', dialCode: '+676', dialCodeSuffixes: [], flag: '🇹🇴', invalid: false },
  { name: 'Kiribati', iso2: 'KI', dialCode: '+686', dialCodeSuffixes: [], flag: '🇰🇮', invalid: false },
  { name: 'Ghana', iso2: 'GH', dialCode: '+233', dialCodeSuffixes: [], flag: '🇬🇭', invalid: false },
  { name: 'Chad', iso2: 'TD', dialCode: '+235', dialCodeSuffixes: [], flag: '🇹🇩', invalid: false },
  { name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263', dialCodeSuffixes: [], flag: '🇿🇼', invalid: false },
  { name: 'Saint Martin', iso2: 'MF', dialCode: '+590', dialCodeSuffixes: [], flag: '🇲🇫', invalid: false },
  { name: 'Mongolia', iso2: 'MN', dialCode: '+976', dialCodeSuffixes: [], flag: '🇲🇳', invalid: false },
  { name: 'Portugal', iso2: 'PT', dialCode: '+351', dialCodeSuffixes: [], flag: '🇵🇹', invalid: false },
  { name: 'American Samoa', iso2: 'AS', dialCode: '+1684', dialCodeSuffixes: [], flag: '🇦🇸', invalid: false },
  { name: 'Republic of the Congo', iso2: 'CG', dialCode: '+242', dialCodeSuffixes: [], flag: '🇨🇬', invalid: false },
  { name: 'Belgium', iso2: 'BE', dialCode: '+32', dialCodeSuffixes: [], flag: '🇧🇪', invalid: false },
  { name: 'Israel', iso2: 'IL', dialCode: '+972', dialCodeSuffixes: [], flag: '🇮🇱', invalid: false },
  { name: 'New Zealand', iso2: 'NZ', dialCode: '+64', dialCodeSuffixes: [], flag: '🇳🇿', invalid: false },
  { name: 'Nicaragua', iso2: 'NI', dialCode: '+505', dialCodeSuffixes: [], flag: '🇳🇮', invalid: false },
  { name: 'Anguilla', iso2: 'AI', dialCode: '+1264', dialCodeSuffixes: [], flag: '🇦🇮', invalid: false },
]
